{
  "hash": "96969745816658e60298a2b3a5fb0cef",
  "result": {
    "markdown": "---\ntitle: \"Análisis de correspondencia con R\"\ndescription: |\n  Análisis para variables categóricas utilizando la metodología de tablas cruzadas con la prueba de chi-cuadrado. Este análisis es una recopilación del libro Multivariate Analysis II: Practical Guide To Principal Component Methods in R.\ncategories: [Chi-cuadrado, Biplot, Componentes Principales]\nauthor:\n  - name: Franklin Santos\n    url: https://franklinsantos.com\n    affiliation: AgriTech Bolivia\n    orcid: 0000-0002-7509-2910\n    email: franklin25santos@gmail.com\ndate: \"2020-11-07\"\nimage: featured.png\ncitation: true\n---\n\n```{=html}\n<style>\nbody {\ntext-align: justify}\n</style>\n```\n\n\n## **Introducción**\n\nExtraer, `ordenar` y `graficar` datos es una tarea que demanda tiempo y cierta habilidad informática. Generalmente, muchos investigadores buscamos datos históricos para observar `tendencias` de *rendimiento*, *producción* y *superficie cultivada*, esto con el propósito de soportar diferentes `investigaciones` del área. Para realizar estas tareas existen diferentes bases de datos de libre acceso, entre ellos está [FAOSTAT](http://www.fao.org/faostat/es/#home). Esta organización proporciona *acceso libre* a datos sobre **alimentación y agricultura** de más de 245 países y 35 regiones, desde 1961 hasta el año más reciente disponible. \n\nLos datos de FAOSTAT habitualmente son descargados en planillas de `Microsoft Excel` y en ésta se va limpiando de forma manual hasta que el resumen de datos sea presentable. Esta actividad requiere tiempo; sin embargo, existen herramientas de programación que pueden `automatizar` este proceso y reducir tiempo en ordenar datos. Una de ellas es [**R**](https://www.r-project.org), la cual es un *lenguaje de programación* y un ambiente de *software libre* para la **ciencia de datos**. Por tanto, nuestro objetivo es `extraer` y `ordenar` datos de la página web de `FAOSTAT` con el uso del paquete `Tidyverse` en el ambiente `R`.\n\n## **Extracción**\n\nPara acceder a FAOSTAT, diríjase al sitio web oficial a traves del enlace <http://www.fao.org/faostat/en/#home>. En la página principal tiene la opción de cambiar el idioma del ingles al español y haga clic en `Acceder a los datos`. Una vez que acceda a esta ventana, haga clic en `cultivos` en la sección de `Producción`, en la cual observará la vista de selección y `descargar datos`. En esta ventana seleccionamos la base de datos a descargar. Para esto siga los siguientes pasos:\n\n![](fao.png)\n\n* Seleccione **países** o **regiones** de interes, en nuestro caso hacemos clic en `regiones` y elegimos los países de `América del Sur`.\n* En la subventana de `elementos` puede seleccionar `Área cosechada` (superficie cultivada), `Rendimiento` y `Producción`. Para nuestro ejemplo elegimos *rendimiento*.\n* El siguiente paso es seleccionar los cultivos o `productos` de interes. En nuestro caso elegimos cuatro cultivos (arroz, maíz, papa y trigo).\n* En la última subventana seleccione los `Años` de interes. Para nuestro ejemplo elegimos todos los años, esto con el propósito de hacer comparación de la tendencia de rendimiento en los países de latinoamérica.\n* El último paso es `descargar` los datos seleccionados. Para esto, la salida de datos debe estar seleccionado en formato `Tabla`, tipo de archivo `CSV` y hacer clic en `Descargar Datos` para guardar en un archivo de proyecto.\n\n## **Ordenación**\n\nA partir de esta etapa se usará la consola de **R** a traves del entorno [RStudio](https://rstudio.com). Para ordenar los datos es recomendable usar el paquete [tidyverse](https://www.tidyverse.org), la cual es una colección obstinada de paquetes R diseñados para la ciencia de datos. Para instalar use este código `install.packages(\"tidyverse\")`.\n\nPara proceder con la ordenación de datos, analizar y/o generar otro tipo de actividades con R, recomiendo crear un proyecto a traves de `RStudio`. Esto facilita el flujo de trabajo dentro de R. Posterior a ello, llame al paquete `tidyverse`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nPara iniciar con el trabajo es necesario que los datos descargados de FAOSTAT se encuentre dentro de los archivos del proyecto.\n\nPara llamar los datos al entorno de R use la siguiente función:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkey_crops <- read_csv(\"FAOSTAT_data_11-18-2020.csv\")\n```\n:::\n\n\nPara verificar el marco de datos en el ambiente R, ejecute la variable `key_crops`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nkey_crops\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2,657 × 14\n   Domain Cod…¹ Domain Area …² Area  Eleme…³ Element Item …⁴ Item  Year …⁵  Year\n   <chr>        <chr>    <dbl> <chr>   <dbl> <chr>     <dbl> <chr>   <dbl> <dbl>\n 1 QC           Crops        9 Arge…    5419 Yield        56 Maize    1961  1961\n 2 QC           Crops        9 Arge…    5419 Yield        56 Maize    1962  1962\n 3 QC           Crops        9 Arge…    5419 Yield        56 Maize    1963  1963\n 4 QC           Crops        9 Arge…    5419 Yield        56 Maize    1964  1964\n 5 QC           Crops        9 Arge…    5419 Yield        56 Maize    1965  1965\n 6 QC           Crops        9 Arge…    5419 Yield        56 Maize    1966  1966\n 7 QC           Crops        9 Arge…    5419 Yield        56 Maize    1967  1967\n 8 QC           Crops        9 Arge…    5419 Yield        56 Maize    1968  1968\n 9 QC           Crops        9 Arge…    5419 Yield        56 Maize    1969  1969\n10 QC           Crops        9 Arge…    5419 Yield        56 Maize    1970  1970\n# … with 2,647 more rows, 4 more variables: Unit <chr>, Value <dbl>,\n#   Flag <chr>, `Flag Description` <chr>, and abbreviated variable names\n#   ¹​`Domain Code`, ²​`Area Code`, ³​`Element Code`, ⁴​`Item Code`, ⁵​`Year Code`\n```\n:::\n:::\n\n\nEn esta salida puede observar `2657` filas u observaciones y `14` columnas o variables. Asimismo, puede verificar los `formatos` de cada variable. Esta base de datos no facilita el uso apropiado para realizar un resumen descriptivo o generar gráficas para observar tendencias.\n\n### Ordenando base de datos\n\nPara este proceso se identificó que la columna de `Area` contiene países de América del Sur; sin embargo, en estas obsevarciones Bolivia tiene texto adicional \"`Bolivia (Plurinational State of)`\". Para eliminar el texto adicional se usa la función `separate(Area, c(\"country\"), sep = \" \")`, el mismo proceso se aplica para `Rice, paddy` en la columa de cultivos `Item`. A partir de la columna `Value` se creó otra columna `mutate(yield = Value / 10000)`, en la cual se hizo la conversión de hectogramos (hg ha^-1^) a toneladas (t ha^-1^). El siguiente paso fue seleccionar cuatro variables de la base de datos `select(country, crop, Year, yield)` y al finalizar este proceso se filtró los países más próximos a Bolivia. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong_crops <- key_crops %>% \n  separate(Area, c(\"country\"), sep = \" \") %>%\n  separate(Item, c(\"crop\"), sep = \",\") %>%\n  mutate(yield = Value / 10000) %>%\n  select(country, crop, Year, yield) %>%\n  filter(country %in% c(\"Argentina\", \n                        \"Bolivia\", \n                        \"Brazil\",\n                        \"Chile\",\n                        \"Paraguay\",\n                        \"Peru\",\n                        \"Uruguay\")\n  )\n```\n:::\n\n\nPodemos observar los datos ordenados ejecutando `long_crops`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong_crops\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,624 × 4\n   country   crop   Year yield\n   <chr>     <chr> <dbl> <dbl>\n 1 Argentina Maize  1961  1.77\n 2 Argentina Maize  1962  1.89\n 3 Argentina Maize  1963  1.65\n 4 Argentina Maize  1964  1.80\n 5 Argentina Maize  1965  1.68\n 6 Argentina Maize  1966  2.15\n 7 Argentina Maize  1967  2.47\n 8 Argentina Maize  1968  1.94\n 9 Argentina Maize  1969  1.93\n10 Argentina Maize  1970  2.33\n# … with 1,614 more rows\n```\n:::\n:::\n\n\nEstos datos tienen 1624 filas y 4 columnas, las cuales estan ordenadas y listas para generar gráficas interactivas o estáticas.\n\n## **Graficando los datos**\n\nGenerar gráficas es muy importante, ya que es más cómodo interpretar, analizar tendencias o identificar asociaciones. Debido a ello, se realizó una figura multipanel.\n\n\n::: {.cell layout=\"l-body-outset\"}\n\n```{.r .cell-code}\nlibrary(plotly)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'plotly'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:ggplot2':\n\n    last_plot\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:graphics':\n\n    layout\n```\n:::\n\n```{.r .cell-code}\np <- long_crops %>%\n  ggplot(aes(Year, yield, color = country)) +\n  geom_line() +\n  facet_wrap(~crop, ncol = 2) +\n  labs(x = \"Year\", y = \"Yield (t ha)\")\nfig <- ggplotly(p)\n\nfig\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-39122d26341c50a3df4f\" style=\"width:100%;height:390px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-39122d26341c50a3df4f\">{\"x\":{\"data\":[{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.7672,1.8936,1.6481,1.801,1.6785,2.1499,2.4663,1.9421,1.9291,2.3299,2.4422,1.862,2.7206,2.8399,2.5081,2.1169,3.278,3.6466,3.1071,2.5703,3.8008,3.0284,3.0303,3.1407,3.5629,3.745,3.1897,3.7744,2.9103,3.4608,4.0444,4.5237,4.3552,4.2371,4.5223,4.0397,4.5557,6.078,5.3702,5.4329,5.4553,6.0791,6.4767,6.3931,7.3587,5.903,7.6655,6.4525,5.576,7.804,6.3503,5.7346,6.6037,6.8409,7.309,7.4427,7.5759,6.0883],\"text\":[\"Year: 1961<br />yield:  1.7672<br />country: Argentina\",\"Year: 1962<br />yield:  1.8936<br />country: Argentina\",\"Year: 1963<br />yield:  1.6481<br />country: Argentina\",\"Year: 1964<br />yield:  1.8010<br />country: Argentina\",\"Year: 1965<br />yield:  1.6785<br />country: Argentina\",\"Year: 1966<br />yield:  2.1499<br />country: Argentina\",\"Year: 1967<br />yield:  2.4663<br />country: Argentina\",\"Year: 1968<br />yield:  1.9421<br />country: Argentina\",\"Year: 1969<br />yield:  1.9291<br />country: Argentina\",\"Year: 1970<br />yield:  2.3299<br />country: Argentina\",\"Year: 1971<br />yield:  2.4422<br />country: Argentina\",\"Year: 1972<br />yield:  1.8620<br />country: Argentina\",\"Year: 1973<br />yield:  2.7206<br />country: Argentina\",\"Year: 1974<br />yield:  2.8399<br />country: Argentina\",\"Year: 1975<br />yield:  2.5081<br />country: Argentina\",\"Year: 1976<br />yield:  2.1169<br />country: Argentina\",\"Year: 1977<br />yield:  3.2780<br />country: Argentina\",\"Year: 1978<br />yield:  3.6466<br />country: Argentina\",\"Year: 1979<br />yield:  3.1071<br />country: Argentina\",\"Year: 1980<br />yield:  2.5703<br />country: Argentina\",\"Year: 1981<br />yield:  3.8008<br />country: Argentina\",\"Year: 1982<br />yield:  3.0284<br />country: Argentina\",\"Year: 1983<br />yield:  3.0303<br />country: Argentina\",\"Year: 1984<br />yield:  3.1407<br />country: Argentina\",\"Year: 1985<br />yield:  3.5629<br />country: Argentina\",\"Year: 1986<br />yield:  3.7450<br />country: Argentina\",\"Year: 1987<br />yield:  3.1897<br />country: Argentina\",\"Year: 1988<br />yield:  3.7744<br />country: Argentina\",\"Year: 1989<br />yield:  2.9103<br />country: Argentina\",\"Year: 1990<br />yield:  3.4608<br />country: Argentina\",\"Year: 1991<br />yield:  4.0444<br />country: Argentina\",\"Year: 1992<br />yield:  4.5237<br />country: Argentina\",\"Year: 1993<br />yield:  4.3552<br />country: Argentina\",\"Year: 1994<br />yield:  4.2371<br />country: Argentina\",\"Year: 1995<br />yield:  4.5223<br />country: Argentina\",\"Year: 1996<br />yield:  4.0397<br />country: Argentina\",\"Year: 1997<br />yield:  4.5557<br />country: Argentina\",\"Year: 1998<br />yield:  6.0780<br />country: Argentina\",\"Year: 1999<br />yield:  5.3702<br />country: Argentina\",\"Year: 2000<br />yield:  5.4329<br />country: Argentina\",\"Year: 2001<br />yield:  5.4553<br />country: Argentina\",\"Year: 2002<br />yield:  6.0791<br />country: Argentina\",\"Year: 2003<br />yield:  6.4767<br />country: Argentina\",\"Year: 2004<br />yield:  6.3931<br />country: Argentina\",\"Year: 2005<br />yield:  7.3587<br />country: Argentina\",\"Year: 2006<br />yield:  5.9030<br />country: Argentina\",\"Year: 2007<br />yield:  7.6655<br />country: Argentina\",\"Year: 2008<br />yield:  6.4525<br />country: Argentina\",\"Year: 2009<br />yield:  5.5760<br />country: Argentina\",\"Year: 2010<br />yield:  7.8040<br />country: Argentina\",\"Year: 2011<br />yield:  6.3503<br />country: Argentina\",\"Year: 2012<br />yield:  5.7346<br />country: Argentina\",\"Year: 2013<br />yield:  6.6037<br />country: Argentina\",\"Year: 2014<br />yield:  6.8409<br />country: Argentina\",\"Year: 2015<br />yield:  7.3090<br />country: Argentina\",\"Year: 2016<br />yield:  7.4427<br />country: Argentina\",\"Year: 2017<br />yield:  7.5759<br />country: Argentina\",\"Year: 2018<br />yield:  6.0883<br />country: Argentina\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Argentina\",\"legendgroup\":\"Argentina\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[10.211,8.2576,8.7699,8.3457,12.217,9.0025,11.0138,9.8431,11.5387,12.3156,10.9653,9.1093,13.0994,17.1584,12.1824,14.1586,15.8872,13.8042,15.4703,13.9415,19.2554,17.775,18.4317,18.5606,21.1124,18.8418,19.996,25.6686,21.1882,20.2747,20.5692,19.9039,21.0314,23.0166,27.4272,22.8877,26.8502,29.3744,23.8938,27.7566,28.3768,25.1347,27.9269,28.8717,28.3917,28.5828,28.6765,27.9412,29.3326,29.6203,29.8649,30.3967,30.7357,31.0609,31.354,32.1969,32.0463,32.3033],\"text\":[\"Year: 1961<br />yield: 10.2110<br />country: Argentina\",\"Year: 1962<br />yield:  8.2576<br />country: Argentina\",\"Year: 1963<br />yield:  8.7699<br />country: Argentina\",\"Year: 1964<br />yield:  8.3457<br />country: Argentina\",\"Year: 1965<br />yield: 12.2170<br />country: Argentina\",\"Year: 1966<br />yield:  9.0025<br />country: Argentina\",\"Year: 1967<br />yield: 11.0138<br />country: Argentina\",\"Year: 1968<br />yield:  9.8431<br />country: Argentina\",\"Year: 1969<br />yield: 11.5387<br />country: Argentina\",\"Year: 1970<br />yield: 12.3156<br />country: Argentina\",\"Year: 1971<br />yield: 10.9653<br />country: Argentina\",\"Year: 1972<br />yield:  9.1093<br />country: Argentina\",\"Year: 1973<br />yield: 13.0994<br />country: Argentina\",\"Year: 1974<br />yield: 17.1584<br />country: Argentina\",\"Year: 1975<br />yield: 12.1824<br />country: Argentina\",\"Year: 1976<br />yield: 14.1586<br />country: Argentina\",\"Year: 1977<br />yield: 15.8872<br />country: Argentina\",\"Year: 1978<br />yield: 13.8042<br />country: Argentina\",\"Year: 1979<br />yield: 15.4703<br />country: Argentina\",\"Year: 1980<br />yield: 13.9415<br />country: Argentina\",\"Year: 1981<br />yield: 19.2554<br />country: Argentina\",\"Year: 1982<br />yield: 17.7750<br />country: Argentina\",\"Year: 1983<br />yield: 18.4317<br />country: Argentina\",\"Year: 1984<br />yield: 18.5606<br />country: Argentina\",\"Year: 1985<br />yield: 21.1124<br />country: Argentina\",\"Year: 1986<br />yield: 18.8418<br />country: Argentina\",\"Year: 1987<br />yield: 19.9960<br />country: Argentina\",\"Year: 1988<br />yield: 25.6686<br />country: Argentina\",\"Year: 1989<br />yield: 21.1882<br />country: Argentina\",\"Year: 1990<br />yield: 20.2747<br />country: Argentina\",\"Year: 1991<br />yield: 20.5692<br />country: Argentina\",\"Year: 1992<br />yield: 19.9039<br />country: Argentina\",\"Year: 1993<br />yield: 21.0314<br />country: Argentina\",\"Year: 1994<br />yield: 23.0166<br />country: Argentina\",\"Year: 1995<br />yield: 27.4272<br />country: Argentina\",\"Year: 1996<br />yield: 22.8877<br />country: Argentina\",\"Year: 1997<br />yield: 26.8502<br />country: Argentina\",\"Year: 1998<br />yield: 29.3744<br />country: Argentina\",\"Year: 1999<br />yield: 23.8938<br />country: Argentina\",\"Year: 2000<br />yield: 27.7566<br />country: Argentina\",\"Year: 2001<br />yield: 28.3768<br />country: Argentina\",\"Year: 2002<br />yield: 25.1347<br />country: Argentina\",\"Year: 2003<br />yield: 27.9269<br />country: Argentina\",\"Year: 2004<br />yield: 28.8717<br />country: Argentina\",\"Year: 2005<br />yield: 28.3917<br />country: Argentina\",\"Year: 2006<br />yield: 28.5828<br />country: Argentina\",\"Year: 2007<br />yield: 28.6765<br />country: Argentina\",\"Year: 2008<br />yield: 27.9412<br />country: Argentina\",\"Year: 2009<br />yield: 29.3326<br />country: Argentina\",\"Year: 2010<br />yield: 29.6203<br />country: Argentina\",\"Year: 2011<br />yield: 29.8649<br />country: Argentina\",\"Year: 2012<br />yield: 30.3967<br />country: Argentina\",\"Year: 2013<br />yield: 30.7357<br />country: Argentina\",\"Year: 2014<br />yield: 31.0609<br />country: Argentina\",\"Year: 2015<br />yield: 31.3540<br />country: Argentina\",\"Year: 2016<br />yield: 32.1969<br />country: Argentina\",\"Year: 2017<br />yield: 32.0463<br />country: Argentina\",\"Year: 2018<br />yield: 32.3033<br />country: Argentina\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Argentina\",\"legendgroup\":\"Argentina\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[3.2391,3.4357,3.4073,3.5172,3.9423,3.5324,3.5096,3.9958,3.9429,3.9941,3.7306,3.5379,3.3965,3.821,3.7946,3.5407,3.532,3.2632,3.0469,3.236,3.5,3.8486,3.6602,3.7419,3.6782,3.8849,3.9185,4.181,4.6711,3.6709,4.0294,5.2075,4.3559,4.2989,5.0306,5.1031,5.3703,4.7762,5.7337,4.7798,5.7495,5.7197,5.4002,6.2661,6.0165,7.061,6.5604,6.8278,6.8842,5.7646,6.7901,6.6617,6.7187,6.5042,6.6989,6.7632,6.5083,6.903],\"text\":[\"Year: 1961<br />yield:  3.2391<br />country: Argentina\",\"Year: 1962<br />yield:  3.4357<br />country: Argentina\",\"Year: 1963<br />yield:  3.4073<br />country: Argentina\",\"Year: 1964<br />yield:  3.5172<br />country: Argentina\",\"Year: 1965<br />yield:  3.9423<br />country: Argentina\",\"Year: 1966<br />yield:  3.5324<br />country: Argentina\",\"Year: 1967<br />yield:  3.5096<br />country: Argentina\",\"Year: 1968<br />yield:  3.9958<br />country: Argentina\",\"Year: 1969<br />yield:  3.9429<br />country: Argentina\",\"Year: 1970<br />yield:  3.9941<br />country: Argentina\",\"Year: 1971<br />yield:  3.7306<br />country: Argentina\",\"Year: 1972<br />yield:  3.5379<br />country: Argentina\",\"Year: 1973<br />yield:  3.3965<br />country: Argentina\",\"Year: 1974<br />yield:  3.8210<br />country: Argentina\",\"Year: 1975<br />yield:  3.7946<br />country: Argentina\",\"Year: 1976<br />yield:  3.5407<br />country: Argentina\",\"Year: 1977<br />yield:  3.5320<br />country: Argentina\",\"Year: 1978<br />yield:  3.2632<br />country: Argentina\",\"Year: 1979<br />yield:  3.0469<br />country: Argentina\",\"Year: 1980<br />yield:  3.2360<br />country: Argentina\",\"Year: 1981<br />yield:  3.5000<br />country: Argentina\",\"Year: 1982<br />yield:  3.8486<br />country: Argentina\",\"Year: 1983<br />yield:  3.6602<br />country: Argentina\",\"Year: 1984<br />yield:  3.7419<br />country: Argentina\",\"Year: 1985<br />yield:  3.6782<br />country: Argentina\",\"Year: 1986<br />yield:  3.8849<br />country: Argentina\",\"Year: 1987<br />yield:  3.9185<br />country: Argentina\",\"Year: 1988<br />yield:  4.1810<br />country: Argentina\",\"Year: 1989<br />yield:  4.6711<br />country: Argentina\",\"Year: 1990<br />yield:  3.6709<br />country: Argentina\",\"Year: 1991<br />yield:  4.0294<br />country: Argentina\",\"Year: 1992<br />yield:  5.2075<br />country: Argentina\",\"Year: 1993<br />yield:  4.3559<br />country: Argentina\",\"Year: 1994<br />yield:  4.2989<br />country: Argentina\",\"Year: 1995<br />yield:  5.0306<br />country: Argentina\",\"Year: 1996<br />yield:  5.1031<br />country: Argentina\",\"Year: 1997<br />yield:  5.3703<br />country: Argentina\",\"Year: 1998<br />yield:  4.7762<br />country: Argentina\",\"Year: 1999<br />yield:  5.7337<br />country: Argentina\",\"Year: 2000<br />yield:  4.7798<br />country: Argentina\",\"Year: 2001<br />yield:  5.7495<br />country: Argentina\",\"Year: 2002<br />yield:  5.7197<br />country: Argentina\",\"Year: 2003<br />yield:  5.4002<br />country: Argentina\",\"Year: 2004<br />yield:  6.2661<br />country: Argentina\",\"Year: 2005<br />yield:  6.0165<br />country: Argentina\",\"Year: 2006<br />yield:  7.0610<br />country: Argentina\",\"Year: 2007<br />yield:  6.5604<br />country: Argentina\",\"Year: 2008<br />yield:  6.8278<br />country: Argentina\",\"Year: 2009<br />yield:  6.8842<br />country: Argentina\",\"Year: 2010<br />yield:  5.7646<br />country: Argentina\",\"Year: 2011<br />yield:  6.7901<br />country: Argentina\",\"Year: 2012<br />yield:  6.6617<br />country: Argentina\",\"Year: 2013<br />yield:  6.7187<br />country: Argentina\",\"Year: 2014<br />yield:  6.5042<br />country: Argentina\",\"Year: 2015<br />yield:  6.6989<br />country: Argentina\",\"Year: 2016<br />yield:  6.7632<br />country: Argentina\",\"Year: 2017<br />yield:  6.5083<br />country: Argentina\",\"Year: 2018<br />yield:  6.9030<br />country: Argentina\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Argentina\",\"legendgroup\":\"Argentina\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.295,1.5222,1.5751,1.8353,1.3212,1.1982,1.2595,0.9833,1.3523,1.3294,1.2667,1.5911,1.6574,1.4103,1.626,1.7045,1.3612,1.7396,1.6934,1.5596,1.4014,2.0501,1.8405,2.3068,1.6177,1.7819,1.8847,1.8344,1.8947,1.8947,1.8972,2.1809,2.3272,2.0237,2.1675,1.9344,2.2426,2.6088,2.3028,2.4873,2.4934,2.2398,2.0361,2.5441,2.6356,2.5302,2.6234,2.8271,1.9628,2.7113,3.5063,3.2199,2.6581,2.6619,2.81,2.8623,3.3047,3.1806],\"text\":[\"Year: 1961<br />yield:  1.2950<br />country: Argentina\",\"Year: 1962<br />yield:  1.5222<br />country: Argentina\",\"Year: 1963<br />yield:  1.5751<br />country: Argentina\",\"Year: 1964<br />yield:  1.8353<br />country: Argentina\",\"Year: 1965<br />yield:  1.3212<br />country: Argentina\",\"Year: 1966<br />yield:  1.1982<br />country: Argentina\",\"Year: 1967<br />yield:  1.2595<br />country: Argentina\",\"Year: 1968<br />yield:  0.9833<br />country: Argentina\",\"Year: 1969<br />yield:  1.3523<br />country: Argentina\",\"Year: 1970<br />yield:  1.3294<br />country: Argentina\",\"Year: 1971<br />yield:  1.2667<br />country: Argentina\",\"Year: 1972<br />yield:  1.5911<br />country: Argentina\",\"Year: 1973<br />yield:  1.6574<br />country: Argentina\",\"Year: 1974<br />yield:  1.4103<br />country: Argentina\",\"Year: 1975<br />yield:  1.6260<br />country: Argentina\",\"Year: 1976<br />yield:  1.7045<br />country: Argentina\",\"Year: 1977<br />yield:  1.3612<br />country: Argentina\",\"Year: 1978<br />yield:  1.7396<br />country: Argentina\",\"Year: 1979<br />yield:  1.6934<br />country: Argentina\",\"Year: 1980<br />yield:  1.5596<br />country: Argentina\",\"Year: 1981<br />yield:  1.4014<br />country: Argentina\",\"Year: 1982<br />yield:  2.0501<br />country: Argentina\",\"Year: 1983<br />yield:  1.8405<br />country: Argentina\",\"Year: 1984<br />yield:  2.3068<br />country: Argentina\",\"Year: 1985<br />yield:  1.6177<br />country: Argentina\",\"Year: 1986<br />yield:  1.7819<br />country: Argentina\",\"Year: 1987<br />yield:  1.8847<br />country: Argentina\",\"Year: 1988<br />yield:  1.8344<br />country: Argentina\",\"Year: 1989<br />yield:  1.8947<br />country: Argentina\",\"Year: 1990<br />yield:  1.8947<br />country: Argentina\",\"Year: 1991<br />yield:  1.8972<br />country: Argentina\",\"Year: 1992<br />yield:  2.1809<br />country: Argentina\",\"Year: 1993<br />yield:  2.3272<br />country: Argentina\",\"Year: 1994<br />yield:  2.0237<br />country: Argentina\",\"Year: 1995<br />yield:  2.1675<br />country: Argentina\",\"Year: 1996<br />yield:  1.9344<br />country: Argentina\",\"Year: 1997<br />yield:  2.2426<br />country: Argentina\",\"Year: 1998<br />yield:  2.6088<br />country: Argentina\",\"Year: 1999<br />yield:  2.3028<br />country: Argentina\",\"Year: 2000<br />yield:  2.4873<br />country: Argentina\",\"Year: 2001<br />yield:  2.4934<br />country: Argentina\",\"Year: 2002<br />yield:  2.2398<br />country: Argentina\",\"Year: 2003<br />yield:  2.0361<br />country: Argentina\",\"Year: 2004<br />yield:  2.5441<br />country: Argentina\",\"Year: 2005<br />yield:  2.6356<br />country: Argentina\",\"Year: 2006<br />yield:  2.5302<br />country: Argentina\",\"Year: 2007<br />yield:  2.6234<br />country: Argentina\",\"Year: 2008<br />yield:  2.8271<br />country: Argentina\",\"Year: 2009<br />yield:  1.9628<br />country: Argentina\",\"Year: 2010<br />yield:  2.7113<br />country: Argentina\",\"Year: 2011<br />yield:  3.5063<br />country: Argentina\",\"Year: 2012<br />yield:  3.2199<br />country: Argentina\",\"Year: 2013<br />yield:  2.6581<br />country: Argentina\",\"Year: 2014<br />yield:  2.6619<br />country: Argentina\",\"Year: 2015<br />yield:  2.8100<br />country: Argentina\",\"Year: 2016<br />yield:  2.8623<br />country: Argentina\",\"Year: 2017<br />yield:  3.3047<br />country: Argentina\",\"Year: 2018<br />yield:  3.1806<br />country: Argentina\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(248,118,109,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Argentina\",\"legendgroup\":\"Argentina\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.2501,1.2399,1.2408,0.9091,1.2949,1.3219,1.3224,1.3224,1.3232,1.2922,1.3037,1.2517,1.2818,1.2605,1.3246,1.5269,1.2616,1.3014,1.3602,1.3063,1.6087,1.5733,1.2927,1.5436,1.5875,1.5554,1.5912,1.5189,1.4353,1.6658,1.5285,1.7534,1.8658,1.8107,1.8526,1.8011,1.506,1.8192,1.7621,2.1259,2.2143,2.167,2.3405,1.7145,2.1859,2.6071,2.1155,2.312,2.8185,2.789,2.4766,2.8517,2.1442,2.1719,2.3929,2.4971,2.2473,2.7282],\"text\":[\"Year: 1961<br />yield:  1.2501<br />country: Bolivia\",\"Year: 1962<br />yield:  1.2399<br />country: Bolivia\",\"Year: 1963<br />yield:  1.2408<br />country: Bolivia\",\"Year: 1964<br />yield:  0.9091<br />country: Bolivia\",\"Year: 1965<br />yield:  1.2949<br />country: Bolivia\",\"Year: 1966<br />yield:  1.3219<br />country: Bolivia\",\"Year: 1967<br />yield:  1.3224<br />country: Bolivia\",\"Year: 1968<br />yield:  1.3224<br />country: Bolivia\",\"Year: 1969<br />yield:  1.3232<br />country: Bolivia\",\"Year: 1970<br />yield:  1.2922<br />country: Bolivia\",\"Year: 1971<br />yield:  1.3037<br />country: Bolivia\",\"Year: 1972<br />yield:  1.2517<br />country: Bolivia\",\"Year: 1973<br />yield:  1.2818<br />country: Bolivia\",\"Year: 1974<br />yield:  1.2605<br />country: Bolivia\",\"Year: 1975<br />yield:  1.3246<br />country: Bolivia\",\"Year: 1976<br />yield:  1.5269<br />country: Bolivia\",\"Year: 1977<br />yield:  1.2616<br />country: Bolivia\",\"Year: 1978<br />yield:  1.3014<br />country: Bolivia\",\"Year: 1979<br />yield:  1.3602<br />country: Bolivia\",\"Year: 1980<br />yield:  1.3063<br />country: Bolivia\",\"Year: 1981<br />yield:  1.6087<br />country: Bolivia\",\"Year: 1982<br />yield:  1.5733<br />country: Bolivia\",\"Year: 1983<br />yield:  1.2927<br />country: Bolivia\",\"Year: 1984<br />yield:  1.5436<br />country: Bolivia\",\"Year: 1985<br />yield:  1.5875<br />country: Bolivia\",\"Year: 1986<br />yield:  1.5554<br />country: Bolivia\",\"Year: 1987<br />yield:  1.5912<br />country: Bolivia\",\"Year: 1988<br />yield:  1.5189<br />country: Bolivia\",\"Year: 1989<br />yield:  1.4353<br />country: Bolivia\",\"Year: 1990<br />yield:  1.6658<br />country: Bolivia\",\"Year: 1991<br />yield:  1.5285<br />country: Bolivia\",\"Year: 1992<br />yield:  1.7534<br />country: Bolivia\",\"Year: 1993<br />yield:  1.8658<br />country: Bolivia\",\"Year: 1994<br />yield:  1.8107<br />country: Bolivia\",\"Year: 1995<br />yield:  1.8526<br />country: Bolivia\",\"Year: 1996<br />yield:  1.8011<br />country: Bolivia\",\"Year: 1997<br />yield:  1.5060<br />country: Bolivia\",\"Year: 1998<br />yield:  1.8192<br />country: Bolivia\",\"Year: 1999<br />yield:  1.7621<br />country: Bolivia\",\"Year: 2000<br />yield:  2.1259<br />country: Bolivia\",\"Year: 2001<br />yield:  2.2143<br />country: Bolivia\",\"Year: 2002<br />yield:  2.1670<br />country: Bolivia\",\"Year: 2003<br />yield:  2.3405<br />country: Bolivia\",\"Year: 2004<br />yield:  1.7145<br />country: Bolivia\",\"Year: 2005<br />yield:  2.1859<br />country: Bolivia\",\"Year: 2006<br />yield:  2.6071<br />country: Bolivia\",\"Year: 2007<br />yield:  2.1155<br />country: Bolivia\",\"Year: 2008<br />yield:  2.3120<br />country: Bolivia\",\"Year: 2009<br />yield:  2.8185<br />country: Bolivia\",\"Year: 2010<br />yield:  2.7890<br />country: Bolivia\",\"Year: 2011<br />yield:  2.4766<br />country: Bolivia\",\"Year: 2012<br />yield:  2.8517<br />country: Bolivia\",\"Year: 2013<br />yield:  2.1442<br />country: Bolivia\",\"Year: 2014<br />yield:  2.1719<br />country: Bolivia\",\"Year: 2015<br />yield:  2.3929<br />country: Bolivia\",\"Year: 2016<br />yield:  2.4971<br />country: Bolivia\",\"Year: 2017<br />yield:  2.2473<br />country: Bolivia\",\"Year: 2018<br />yield:  2.7282<br />country: Bolivia\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(196,154,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Bolivia\",\"legendgroup\":\"Bolivia\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[4.8,4.85,4.8691,5.1,5,4.98,5.0501,6.8091,6.8048,6.8947,7.1959,6.2848,6.3118,6.3403,6.5323,6.3489,5.2625,4.6989,4.4726,4.6675,4.8925,5.648,2.9259,4.6352,4.7099,4.8684,5.7386,5.7469,4.9874,5.1779,4.9405,4.4055,4.5668,4.7284,4.8392,4.9784,5.1632,4.4809,5.5814,5.7531,5.6778,5.717,5.7126,5.6423,5.6699,5.5759,5.3667,5.4067,5.2309,5.6579,5.7021,5.3211,5.6017,6.0352,5.8962,5.9092,5.8677,6.4211],\"text\":[\"Year: 1961<br />yield:  4.8000<br />country: Bolivia\",\"Year: 1962<br />yield:  4.8500<br />country: Bolivia\",\"Year: 1963<br />yield:  4.8691<br />country: Bolivia\",\"Year: 1964<br />yield:  5.1000<br />country: Bolivia\",\"Year: 1965<br />yield:  5.0000<br />country: Bolivia\",\"Year: 1966<br />yield:  4.9800<br />country: Bolivia\",\"Year: 1967<br />yield:  5.0501<br />country: Bolivia\",\"Year: 1968<br />yield:  6.8091<br />country: Bolivia\",\"Year: 1969<br />yield:  6.8048<br />country: Bolivia\",\"Year: 1970<br />yield:  6.8947<br />country: Bolivia\",\"Year: 1971<br />yield:  7.1959<br />country: Bolivia\",\"Year: 1972<br />yield:  6.2848<br />country: Bolivia\",\"Year: 1973<br />yield:  6.3118<br />country: Bolivia\",\"Year: 1974<br />yield:  6.3403<br />country: Bolivia\",\"Year: 1975<br />yield:  6.5323<br />country: Bolivia\",\"Year: 1976<br />yield:  6.3489<br />country: Bolivia\",\"Year: 1977<br />yield:  5.2625<br />country: Bolivia\",\"Year: 1978<br />yield:  4.6989<br />country: Bolivia\",\"Year: 1979<br />yield:  4.4726<br />country: Bolivia\",\"Year: 1980<br />yield:  4.6675<br />country: Bolivia\",\"Year: 1981<br />yield:  4.8925<br />country: Bolivia\",\"Year: 1982<br />yield:  5.6480<br />country: Bolivia\",\"Year: 1983<br />yield:  2.9259<br />country: Bolivia\",\"Year: 1984<br />yield:  4.6352<br />country: Bolivia\",\"Year: 1985<br />yield:  4.7099<br />country: Bolivia\",\"Year: 1986<br />yield:  4.8684<br />country: Bolivia\",\"Year: 1987<br />yield:  5.7386<br />country: Bolivia\",\"Year: 1988<br />yield:  5.7469<br />country: Bolivia\",\"Year: 1989<br />yield:  4.9874<br />country: Bolivia\",\"Year: 1990<br />yield:  5.1779<br />country: Bolivia\",\"Year: 1991<br />yield:  4.9405<br />country: Bolivia\",\"Year: 1992<br />yield:  4.4055<br />country: Bolivia\",\"Year: 1993<br />yield:  4.5668<br />country: Bolivia\",\"Year: 1994<br />yield:  4.7284<br />country: Bolivia\",\"Year: 1995<br />yield:  4.8392<br />country: Bolivia\",\"Year: 1996<br />yield:  4.9784<br />country: Bolivia\",\"Year: 1997<br />yield:  5.1632<br />country: Bolivia\",\"Year: 1998<br />yield:  4.4809<br />country: Bolivia\",\"Year: 1999<br />yield:  5.5814<br />country: Bolivia\",\"Year: 2000<br />yield:  5.7531<br />country: Bolivia\",\"Year: 2001<br />yield:  5.6778<br />country: Bolivia\",\"Year: 2002<br />yield:  5.7170<br />country: Bolivia\",\"Year: 2003<br />yield:  5.7126<br />country: Bolivia\",\"Year: 2004<br />yield:  5.6423<br />country: Bolivia\",\"Year: 2005<br />yield:  5.6699<br />country: Bolivia\",\"Year: 2006<br />yield:  5.5759<br />country: Bolivia\",\"Year: 2007<br />yield:  5.3667<br />country: Bolivia\",\"Year: 2008<br />yield:  5.4067<br />country: Bolivia\",\"Year: 2009<br />yield:  5.2309<br />country: Bolivia\",\"Year: 2010<br />yield:  5.6579<br />country: Bolivia\",\"Year: 2011<br />yield:  5.7021<br />country: Bolivia\",\"Year: 2012<br />yield:  5.3211<br />country: Bolivia\",\"Year: 2013<br />yield:  5.6017<br />country: Bolivia\",\"Year: 2014<br />yield:  6.0352<br />country: Bolivia\",\"Year: 2015<br />yield:  5.8962<br />country: Bolivia\",\"Year: 2016<br />yield:  5.9092<br />country: Bolivia\",\"Year: 2017<br />yield:  5.8677<br />country: Bolivia\",\"Year: 2018<br />yield:  6.4211<br />country: Bolivia\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(196,154,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Bolivia\",\"legendgroup\":\"Bolivia\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.4443,1.4428,1.4778,1.5,1.5643,1.5426,1.8443,1.8845,1.5281,1.3157,1.5965,1.6608,1.666,1.5985,1.6931,1.5747,1.7505,1.4146,1.479,1.4397,1.5976,1.5961,1.4167,1.4381,1.5352,1.4833,1.7574,1.782,2.1586,1.9314,2.1017,1.8341,1.7774,1.8134,2.0357,2.623,2.0256,2.0854,1.4169,1.9134,2.2753,1.9976,2.9983,2.1771,2.544,2.6512,2.0711,2.1737,2.2001,2.2757,2.4009,3.0137,2.6633,2.7672,3.1699,2.4829,2.7692,3.1875],\"text\":[\"Year: 1961<br />yield:  1.4443<br />country: Bolivia\",\"Year: 1962<br />yield:  1.4428<br />country: Bolivia\",\"Year: 1963<br />yield:  1.4778<br />country: Bolivia\",\"Year: 1964<br />yield:  1.5000<br />country: Bolivia\",\"Year: 1965<br />yield:  1.5643<br />country: Bolivia\",\"Year: 1966<br />yield:  1.5426<br />country: Bolivia\",\"Year: 1967<br />yield:  1.8443<br />country: Bolivia\",\"Year: 1968<br />yield:  1.8845<br />country: Bolivia\",\"Year: 1969<br />yield:  1.5281<br />country: Bolivia\",\"Year: 1970<br />yield:  1.3157<br />country: Bolivia\",\"Year: 1971<br />yield:  1.5965<br />country: Bolivia\",\"Year: 1972<br />yield:  1.6608<br />country: Bolivia\",\"Year: 1973<br />yield:  1.6660<br />country: Bolivia\",\"Year: 1974<br />yield:  1.5985<br />country: Bolivia\",\"Year: 1975<br />yield:  1.6931<br />country: Bolivia\",\"Year: 1976<br />yield:  1.5747<br />country: Bolivia\",\"Year: 1977<br />yield:  1.7505<br />country: Bolivia\",\"Year: 1978<br />yield:  1.4146<br />country: Bolivia\",\"Year: 1979<br />yield:  1.4790<br />country: Bolivia\",\"Year: 1980<br />yield:  1.4397<br />country: Bolivia\",\"Year: 1981<br />yield:  1.5976<br />country: Bolivia\",\"Year: 1982<br />yield:  1.5961<br />country: Bolivia\",\"Year: 1983<br />yield:  1.4167<br />country: Bolivia\",\"Year: 1984<br />yield:  1.4381<br />country: Bolivia\",\"Year: 1985<br />yield:  1.5352<br />country: Bolivia\",\"Year: 1986<br />yield:  1.4833<br />country: Bolivia\",\"Year: 1987<br />yield:  1.7574<br />country: Bolivia\",\"Year: 1988<br />yield:  1.7820<br />country: Bolivia\",\"Year: 1989<br />yield:  2.1586<br />country: Bolivia\",\"Year: 1990<br />yield:  1.9314<br />country: Bolivia\",\"Year: 1991<br />yield:  2.1017<br />country: Bolivia\",\"Year: 1992<br />yield:  1.8341<br />country: Bolivia\",\"Year: 1993<br />yield:  1.7774<br />country: Bolivia\",\"Year: 1994<br />yield:  1.8134<br />country: Bolivia\",\"Year: 1995<br />yield:  2.0357<br />country: Bolivia\",\"Year: 1996<br />yield:  2.6230<br />country: Bolivia\",\"Year: 1997<br />yield:  2.0256<br />country: Bolivia\",\"Year: 1998<br />yield:  2.0854<br />country: Bolivia\",\"Year: 1999<br />yield:  1.4169<br />country: Bolivia\",\"Year: 2000<br />yield:  1.9134<br />country: Bolivia\",\"Year: 2001<br />yield:  2.2753<br />country: Bolivia\",\"Year: 2002<br />yield:  1.9976<br />country: Bolivia\",\"Year: 2003<br />yield:  2.9983<br />country: Bolivia\",\"Year: 2004<br />yield:  2.1771<br />country: Bolivia\",\"Year: 2005<br />yield:  2.5440<br />country: Bolivia\",\"Year: 2006<br />yield:  2.6512<br />country: Bolivia\",\"Year: 2007<br />yield:  2.0711<br />country: Bolivia\",\"Year: 2008<br />yield:  2.1737<br />country: Bolivia\",\"Year: 2009<br />yield:  2.2001<br />country: Bolivia\",\"Year: 2010<br />yield:  2.2757<br />country: Bolivia\",\"Year: 2011<br />yield:  2.4009<br />country: Bolivia\",\"Year: 2012<br />yield:  3.0137<br />country: Bolivia\",\"Year: 2013<br />yield:  2.6633<br />country: Bolivia\",\"Year: 2014<br />yield:  2.7672<br />country: Bolivia\",\"Year: 2015<br />yield:  3.1699<br />country: Bolivia\",\"Year: 2016<br />yield:  2.4829<br />country: Bolivia\",\"Year: 2017<br />yield:  2.7692<br />country: Bolivia\",\"Year: 2018<br />yield:  3.1875<br />country: Bolivia\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(196,154,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Bolivia\",\"legendgroup\":\"Bolivia\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[0.5625,0.5,0.5189,0.5229,0.873,0.55,0.6,0.6,0.6954,0.7,0.7862,0.8333,0.8278,0.8489,0.8034,0.8639,0.653,0.6456,0.6909,0.5992,0.6943,0.6845,0.6045,0.7936,0.7415,0.7642,0.8079,0.767,0.6962,0.648,0.9339,0.8088,1.032,0.7519,0.9746,0.749,1.0641,0.9042,0.8677,0.8492,0.989,0.885,0.9878,1.0665,1.0741,1.1113,0.921,1.2931,1.2862,1.392,0.9731,0.9186,1.1167,1.0652,1.7208,1.4334,0.8848,1.5117],\"text\":[\"Year: 1961<br />yield:  0.5625<br />country: Bolivia\",\"Year: 1962<br />yield:  0.5000<br />country: Bolivia\",\"Year: 1963<br />yield:  0.5189<br />country: Bolivia\",\"Year: 1964<br />yield:  0.5229<br />country: Bolivia\",\"Year: 1965<br />yield:  0.8730<br />country: Bolivia\",\"Year: 1966<br />yield:  0.5500<br />country: Bolivia\",\"Year: 1967<br />yield:  0.6000<br />country: Bolivia\",\"Year: 1968<br />yield:  0.6000<br />country: Bolivia\",\"Year: 1969<br />yield:  0.6954<br />country: Bolivia\",\"Year: 1970<br />yield:  0.7000<br />country: Bolivia\",\"Year: 1971<br />yield:  0.7862<br />country: Bolivia\",\"Year: 1972<br />yield:  0.8333<br />country: Bolivia\",\"Year: 1973<br />yield:  0.8278<br />country: Bolivia\",\"Year: 1974<br />yield:  0.8489<br />country: Bolivia\",\"Year: 1975<br />yield:  0.8034<br />country: Bolivia\",\"Year: 1976<br />yield:  0.8639<br />country: Bolivia\",\"Year: 1977<br />yield:  0.6530<br />country: Bolivia\",\"Year: 1978<br />yield:  0.6456<br />country: Bolivia\",\"Year: 1979<br />yield:  0.6909<br />country: Bolivia\",\"Year: 1980<br />yield:  0.5992<br />country: Bolivia\",\"Year: 1981<br />yield:  0.6943<br />country: Bolivia\",\"Year: 1982<br />yield:  0.6845<br />country: Bolivia\",\"Year: 1983<br />yield:  0.6045<br />country: Bolivia\",\"Year: 1984<br />yield:  0.7936<br />country: Bolivia\",\"Year: 1985<br />yield:  0.7415<br />country: Bolivia\",\"Year: 1986<br />yield:  0.7642<br />country: Bolivia\",\"Year: 1987<br />yield:  0.8079<br />country: Bolivia\",\"Year: 1988<br />yield:  0.7670<br />country: Bolivia\",\"Year: 1989<br />yield:  0.6962<br />country: Bolivia\",\"Year: 1990<br />yield:  0.6480<br />country: Bolivia\",\"Year: 1991<br />yield:  0.9339<br />country: Bolivia\",\"Year: 1992<br />yield:  0.8088<br />country: Bolivia\",\"Year: 1993<br />yield:  1.0320<br />country: Bolivia\",\"Year: 1994<br />yield:  0.7519<br />country: Bolivia\",\"Year: 1995<br />yield:  0.9746<br />country: Bolivia\",\"Year: 1996<br />yield:  0.7490<br />country: Bolivia\",\"Year: 1997<br />yield:  1.0641<br />country: Bolivia\",\"Year: 1998<br />yield:  0.9042<br />country: Bolivia\",\"Year: 1999<br />yield:  0.8677<br />country: Bolivia\",\"Year: 2000<br />yield:  0.8492<br />country: Bolivia\",\"Year: 2001<br />yield:  0.9890<br />country: Bolivia\",\"Year: 2002<br />yield:  0.8850<br />country: Bolivia\",\"Year: 2003<br />yield:  0.9878<br />country: Bolivia\",\"Year: 2004<br />yield:  1.0665<br />country: Bolivia\",\"Year: 2005<br />yield:  1.0741<br />country: Bolivia\",\"Year: 2006<br />yield:  1.1113<br />country: Bolivia\",\"Year: 2007<br />yield:  0.9210<br />country: Bolivia\",\"Year: 2008<br />yield:  1.2931<br />country: Bolivia\",\"Year: 2009<br />yield:  1.2862<br />country: Bolivia\",\"Year: 2010<br />yield:  1.3920<br />country: Bolivia\",\"Year: 2011<br />yield:  0.9731<br />country: Bolivia\",\"Year: 2012<br />yield:  0.9186<br />country: Bolivia\",\"Year: 2013<br />yield:  1.1167<br />country: Bolivia\",\"Year: 2014<br />yield:  1.0652<br />country: Bolivia\",\"Year: 2015<br />yield:  1.7208<br />country: Bolivia\",\"Year: 2016<br />yield:  1.4334<br />country: Bolivia\",\"Year: 2017<br />yield:  0.8848<br />country: Bolivia\",\"Year: 2018<br />yield:  1.5117<br />country: Bolivia\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(196,154,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Bolivia\",\"legendgroup\":\"Bolivia\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.3123,1.3048,1.3092,1.1606,1.3809,1.3066,1.3828,1.3369,1.3149,1.4421,1.3393,1.413,1.4295,1.5248,1.5048,1.5967,1.6322,1.2197,1.4406,1.779,1.833,1.7308,1.7496,1.761,1.8662,1.6486,1.9843,1.8775,2.0582,1.8735,1.8084,2.2828,2.5321,2.3629,2.6005,2.4761,2.6228,2.7964,2.7765,2.7182,3.4019,3.0559,3.7273,3.3671,3.0403,3.3823,3.7852,4.08,3.7145,4.3667,4.2107,5.0057,5.2536,5.1761,5.5353,4.2877,5.6183,5.1044],\"text\":[\"Year: 1961<br />yield:  1.3123<br />country: Brazil\",\"Year: 1962<br />yield:  1.3048<br />country: Brazil\",\"Year: 1963<br />yield:  1.3092<br />country: Brazil\",\"Year: 1964<br />yield:  1.1606<br />country: Brazil\",\"Year: 1965<br />yield:  1.3809<br />country: Brazil\",\"Year: 1966<br />yield:  1.3066<br />country: Brazil\",\"Year: 1967<br />yield:  1.3828<br />country: Brazil\",\"Year: 1968<br />yield:  1.3369<br />country: Brazil\",\"Year: 1969<br />yield:  1.3149<br />country: Brazil\",\"Year: 1970<br />yield:  1.4421<br />country: Brazil\",\"Year: 1971<br />yield:  1.3393<br />country: Brazil\",\"Year: 1972<br />yield:  1.4130<br />country: Brazil\",\"Year: 1973<br />yield:  1.4295<br />country: Brazil\",\"Year: 1974<br />yield:  1.5248<br />country: Brazil\",\"Year: 1975<br />yield:  1.5048<br />country: Brazil\",\"Year: 1976<br />yield:  1.5967<br />country: Brazil\",\"Year: 1977<br />yield:  1.6322<br />country: Brazil\",\"Year: 1978<br />yield:  1.2197<br />country: Brazil\",\"Year: 1979<br />yield:  1.4406<br />country: Brazil\",\"Year: 1980<br />yield:  1.7790<br />country: Brazil\",\"Year: 1981<br />yield:  1.8330<br />country: Brazil\",\"Year: 1982<br />yield:  1.7308<br />country: Brazil\",\"Year: 1983<br />yield:  1.7496<br />country: Brazil\",\"Year: 1984<br />yield:  1.7610<br />country: Brazil\",\"Year: 1985<br />yield:  1.8662<br />country: Brazil\",\"Year: 1986<br />yield:  1.6486<br />country: Brazil\",\"Year: 1987<br />yield:  1.9843<br />country: Brazil\",\"Year: 1988<br />yield:  1.8775<br />country: Brazil\",\"Year: 1989<br />yield:  2.0582<br />country: Brazil\",\"Year: 1990<br />yield:  1.8735<br />country: Brazil\",\"Year: 1991<br />yield:  1.8084<br />country: Brazil\",\"Year: 1992<br />yield:  2.2828<br />country: Brazil\",\"Year: 1993<br />yield:  2.5321<br />country: Brazil\",\"Year: 1994<br />yield:  2.3629<br />country: Brazil\",\"Year: 1995<br />yield:  2.6005<br />country: Brazil\",\"Year: 1996<br />yield:  2.4761<br />country: Brazil\",\"Year: 1997<br />yield:  2.6228<br />country: Brazil\",\"Year: 1998<br />yield:  2.7964<br />country: Brazil\",\"Year: 1999<br />yield:  2.7765<br />country: Brazil\",\"Year: 2000<br />yield:  2.7182<br />country: Brazil\",\"Year: 2001<br />yield:  3.4019<br />country: Brazil\",\"Year: 2002<br />yield:  3.0559<br />country: Brazil\",\"Year: 2003<br />yield:  3.7273<br />country: Brazil\",\"Year: 2004<br />yield:  3.3671<br />country: Brazil\",\"Year: 2005<br />yield:  3.0403<br />country: Brazil\",\"Year: 2006<br />yield:  3.3823<br />country: Brazil\",\"Year: 2007<br />yield:  3.7852<br />country: Brazil\",\"Year: 2008<br />yield:  4.0800<br />country: Brazil\",\"Year: 2009<br />yield:  3.7145<br />country: Brazil\",\"Year: 2010<br />yield:  4.3667<br />country: Brazil\",\"Year: 2011<br />yield:  4.2107<br />country: Brazil\",\"Year: 2012<br />yield:  5.0057<br />country: Brazil\",\"Year: 2013<br />yield:  5.2536<br />country: Brazil\",\"Year: 2014<br />yield:  5.1761<br />country: Brazil\",\"Year: 2015<br />yield:  5.5353<br />country: Brazil\",\"Year: 2016<br />yield:  4.2877<br />country: Brazil\",\"Year: 2017<br />yield:  5.6183<br />country: Brazil\",\"Year: 2018<br />yield:  5.1044<br />country: Brazil\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(83,180,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Brazil\",\"legendgroup\":\"Brazil\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[5.6485,5.7792,5.8451,6.0564,6.1598,6.6669,6.745,7.0855,6.8152,7.394,7.5958,7.8515,7.0868,8.6968,8.6539,9.5047,9.6866,9.5302,10.5536,10.7107,11.1835,11.8067,10.8037,12.5766,12.5401,11.402,13.2362,13.2735,13.5867,14.1084,14.0264,14.0432,14.609,14.4802,15.2304,14.6506,15.2748,15.6439,16.4604,17.1813,18.4997,19.4038,20.3425,21.3525,22.0095,22.3802,24.0356,25.3729,24.8299,25.8859,26.2528,27.4457,27.7517,27.941,29.3159,29.6622,30.9411,31.176],\"text\":[\"Year: 1961<br />yield:  5.6485<br />country: Brazil\",\"Year: 1962<br />yield:  5.7792<br />country: Brazil\",\"Year: 1963<br />yield:  5.8451<br />country: Brazil\",\"Year: 1964<br />yield:  6.0564<br />country: Brazil\",\"Year: 1965<br />yield:  6.1598<br />country: Brazil\",\"Year: 1966<br />yield:  6.6669<br />country: Brazil\",\"Year: 1967<br />yield:  6.7450<br />country: Brazil\",\"Year: 1968<br />yield:  7.0855<br />country: Brazil\",\"Year: 1969<br />yield:  6.8152<br />country: Brazil\",\"Year: 1970<br />yield:  7.3940<br />country: Brazil\",\"Year: 1971<br />yield:  7.5958<br />country: Brazil\",\"Year: 1972<br />yield:  7.8515<br />country: Brazil\",\"Year: 1973<br />yield:  7.0868<br />country: Brazil\",\"Year: 1974<br />yield:  8.6968<br />country: Brazil\",\"Year: 1975<br />yield:  8.6539<br />country: Brazil\",\"Year: 1976<br />yield:  9.5047<br />country: Brazil\",\"Year: 1977<br />yield:  9.6866<br />country: Brazil\",\"Year: 1978<br />yield:  9.5302<br />country: Brazil\",\"Year: 1979<br />yield: 10.5536<br />country: Brazil\",\"Year: 1980<br />yield: 10.7107<br />country: Brazil\",\"Year: 1981<br />yield: 11.1835<br />country: Brazil\",\"Year: 1982<br />yield: 11.8067<br />country: Brazil\",\"Year: 1983<br />yield: 10.8037<br />country: Brazil\",\"Year: 1984<br />yield: 12.5766<br />country: Brazil\",\"Year: 1985<br />yield: 12.5401<br />country: Brazil\",\"Year: 1986<br />yield: 11.4020<br />country: Brazil\",\"Year: 1987<br />yield: 13.2362<br />country: Brazil\",\"Year: 1988<br />yield: 13.2735<br />country: Brazil\",\"Year: 1989<br />yield: 13.5867<br />country: Brazil\",\"Year: 1990<br />yield: 14.1084<br />country: Brazil\",\"Year: 1991<br />yield: 14.0264<br />country: Brazil\",\"Year: 1992<br />yield: 14.0432<br />country: Brazil\",\"Year: 1993<br />yield: 14.6090<br />country: Brazil\",\"Year: 1994<br />yield: 14.4802<br />country: Brazil\",\"Year: 1995<br />yield: 15.2304<br />country: Brazil\",\"Year: 1996<br />yield: 14.6506<br />country: Brazil\",\"Year: 1997<br />yield: 15.2748<br />country: Brazil\",\"Year: 1998<br />yield: 15.6439<br />country: Brazil\",\"Year: 1999<br />yield: 16.4604<br />country: Brazil\",\"Year: 2000<br />yield: 17.1813<br />country: Brazil\",\"Year: 2001<br />yield: 18.4997<br />country: Brazil\",\"Year: 2002<br />yield: 19.4038<br />country: Brazil\",\"Year: 2003<br />yield: 20.3425<br />country: Brazil\",\"Year: 2004<br />yield: 21.3525<br />country: Brazil\",\"Year: 2005<br />yield: 22.0095<br />country: Brazil\",\"Year: 2006<br />yield: 22.3802<br />country: Brazil\",\"Year: 2007<br />yield: 24.0356<br />country: Brazil\",\"Year: 2008<br />yield: 25.3729<br />country: Brazil\",\"Year: 2009<br />yield: 24.8299<br />country: Brazil\",\"Year: 2010<br />yield: 25.8859<br />country: Brazil\",\"Year: 2011<br />yield: 26.2528<br />country: Brazil\",\"Year: 2012<br />yield: 27.4457<br />country: Brazil\",\"Year: 2013<br />yield: 27.7517<br />country: Brazil\",\"Year: 2014<br />yield: 27.9410<br />country: Brazil\",\"Year: 2015<br />yield: 29.3159<br />country: Brazil\",\"Year: 2016<br />yield: 29.6622<br />country: Brazil\",\"Year: 2017<br />yield: 30.9411<br />country: Brazil\",\"Year: 2018<br />yield: 31.1760<br />country: Brazil\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(83,180,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Brazil\",\"legendgroup\":\"Brazil\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.6989,1.6589,1.5423,1.5171,1.641,1.4487,1.5828,1.4919,1.3838,1.5169,1.384,1.4914,1.4933,1.45,1.4665,1.4658,1.5009,1.2974,1.3931,1.5658,1.3485,1.6158,1.5155,1.6869,1.898,1.861,1.7375,1.9806,2.0993,1.8803,2.302,2.1349,2.2912,2.3876,2.5668,2.6578,2.731,2.5198,3.0708,3.0382,3.2405,3.3246,3.249,3.5565,3.3691,3.8798,3.826,4.2311,4.4049,4.1271,4.8956,4.786,5.0071,5.2013,5.7525,5.4643,6.2131,6.3123],\"text\":[\"Year: 1961<br />yield:  1.6989<br />country: Brazil\",\"Year: 1962<br />yield:  1.6589<br />country: Brazil\",\"Year: 1963<br />yield:  1.5423<br />country: Brazil\",\"Year: 1964<br />yield:  1.5171<br />country: Brazil\",\"Year: 1965<br />yield:  1.6410<br />country: Brazil\",\"Year: 1966<br />yield:  1.4487<br />country: Brazil\",\"Year: 1967<br />yield:  1.5828<br />country: Brazil\",\"Year: 1968<br />yield:  1.4919<br />country: Brazil\",\"Year: 1969<br />yield:  1.3838<br />country: Brazil\",\"Year: 1970<br />yield:  1.5169<br />country: Brazil\",\"Year: 1971<br />yield:  1.3840<br />country: Brazil\",\"Year: 1972<br />yield:  1.4914<br />country: Brazil\",\"Year: 1973<br />yield:  1.4933<br />country: Brazil\",\"Year: 1974<br />yield:  1.4500<br />country: Brazil\",\"Year: 1975<br />yield:  1.4665<br />country: Brazil\",\"Year: 1976<br />yield:  1.4658<br />country: Brazil\",\"Year: 1977<br />yield:  1.5009<br />country: Brazil\",\"Year: 1978<br />yield:  1.2974<br />country: Brazil\",\"Year: 1979<br />yield:  1.3931<br />country: Brazil\",\"Year: 1980<br />yield:  1.5658<br />country: Brazil\",\"Year: 1981<br />yield:  1.3485<br />country: Brazil\",\"Year: 1982<br />yield:  1.6158<br />country: Brazil\",\"Year: 1983<br />yield:  1.5155<br />country: Brazil\",\"Year: 1984<br />yield:  1.6869<br />country: Brazil\",\"Year: 1985<br />yield:  1.8980<br />country: Brazil\",\"Year: 1986<br />yield:  1.8610<br />country: Brazil\",\"Year: 1987<br />yield:  1.7375<br />country: Brazil\",\"Year: 1988<br />yield:  1.9806<br />country: Brazil\",\"Year: 1989<br />yield:  2.0993<br />country: Brazil\",\"Year: 1990<br />yield:  1.8803<br />country: Brazil\",\"Year: 1991<br />yield:  2.3020<br />country: Brazil\",\"Year: 1992<br />yield:  2.1349<br />country: Brazil\",\"Year: 1993<br />yield:  2.2912<br />country: Brazil\",\"Year: 1994<br />yield:  2.3876<br />country: Brazil\",\"Year: 1995<br />yield:  2.5668<br />country: Brazil\",\"Year: 1996<br />yield:  2.6578<br />country: Brazil\",\"Year: 1997<br />yield:  2.7310<br />country: Brazil\",\"Year: 1998<br />yield:  2.5198<br />country: Brazil\",\"Year: 1999<br />yield:  3.0708<br />country: Brazil\",\"Year: 2000<br />yield:  3.0382<br />country: Brazil\",\"Year: 2001<br />yield:  3.2405<br />country: Brazil\",\"Year: 2002<br />yield:  3.3246<br />country: Brazil\",\"Year: 2003<br />yield:  3.2490<br />country: Brazil\",\"Year: 2004<br />yield:  3.5565<br />country: Brazil\",\"Year: 2005<br />yield:  3.3691<br />country: Brazil\",\"Year: 2006<br />yield:  3.8798<br />country: Brazil\",\"Year: 2007<br />yield:  3.8260<br />country: Brazil\",\"Year: 2008<br />yield:  4.2311<br />country: Brazil\",\"Year: 2009<br />yield:  4.4049<br />country: Brazil\",\"Year: 2010<br />yield:  4.1271<br />country: Brazil\",\"Year: 2011<br />yield:  4.8956<br />country: Brazil\",\"Year: 2012<br />yield:  4.7860<br />country: Brazil\",\"Year: 2013<br />yield:  5.0071<br />country: Brazil\",\"Year: 2014<br />yield:  5.2013<br />country: Brazil\",\"Year: 2015<br />yield:  5.7525<br />country: Brazil\",\"Year: 2016<br />yield:  5.4643<br />country: Brazil\",\"Year: 2017<br />yield:  6.2131<br />country: Brazil\",\"Year: 2018<br />yield:  6.3123<br />country: Brazil\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(83,180,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Brazil\",\"legendgroup\":\"Brazil\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[0.533,0.9491,0.4945,0.8765,0.7636,0.8573,0.7574,0.8825,0.9762,0.9731,0.8865,0.4237,1.1044,1.1568,0.61,0.9084,0.6552,0.9572,0.7641,0.8653,1.1508,0.646,1.1903,1.1387,1.614,1.4466,1.7654,1.6528,1.6925,1.154,1.4232,1.4295,1.4825,1.5541,1.542,1.8334,1.6359,1.6111,1.9699,1.5156,1.9488,1.4754,2.4035,2.0728,1.9735,1.5927,2.2199,2.5497,2.0802,2.8288,2.6602,2.31,2.7491,2.2088,2.2278,3.1551,2.279,2.6238],\"text\":[\"Year: 1961<br />yield:  0.5330<br />country: Brazil\",\"Year: 1962<br />yield:  0.9491<br />country: Brazil\",\"Year: 1963<br />yield:  0.4945<br />country: Brazil\",\"Year: 1964<br />yield:  0.8765<br />country: Brazil\",\"Year: 1965<br />yield:  0.7636<br />country: Brazil\",\"Year: 1966<br />yield:  0.8573<br />country: Brazil\",\"Year: 1967<br />yield:  0.7574<br />country: Brazil\",\"Year: 1968<br />yield:  0.8825<br />country: Brazil\",\"Year: 1969<br />yield:  0.9762<br />country: Brazil\",\"Year: 1970<br />yield:  0.9731<br />country: Brazil\",\"Year: 1971<br />yield:  0.8865<br />country: Brazil\",\"Year: 1972<br />yield:  0.4237<br />country: Brazil\",\"Year: 1973<br />yield:  1.1044<br />country: Brazil\",\"Year: 1974<br />yield:  1.1568<br />country: Brazil\",\"Year: 1975<br />yield:  0.6100<br />country: Brazil\",\"Year: 1976<br />yield:  0.9084<br />country: Brazil\",\"Year: 1977<br />yield:  0.6552<br />country: Brazil\",\"Year: 1978<br />yield:  0.9572<br />country: Brazil\",\"Year: 1979<br />yield:  0.7641<br />country: Brazil\",\"Year: 1980<br />yield:  0.8653<br />country: Brazil\",\"Year: 1981<br />yield:  1.1508<br />country: Brazil\",\"Year: 1982<br />yield:  0.6460<br />country: Brazil\",\"Year: 1983<br />yield:  1.1903<br />country: Brazil\",\"Year: 1984<br />yield:  1.1387<br />country: Brazil\",\"Year: 1985<br />yield:  1.6140<br />country: Brazil\",\"Year: 1986<br />yield:  1.4466<br />country: Brazil\",\"Year: 1987<br />yield:  1.7654<br />country: Brazil\",\"Year: 1988<br />yield:  1.6528<br />country: Brazil\",\"Year: 1989<br />yield:  1.6925<br />country: Brazil\",\"Year: 1990<br />yield:  1.1540<br />country: Brazil\",\"Year: 1991<br />yield:  1.4232<br />country: Brazil\",\"Year: 1992<br />yield:  1.4295<br />country: Brazil\",\"Year: 1993<br />yield:  1.4825<br />country: Brazil\",\"Year: 1994<br />yield:  1.5541<br />country: Brazil\",\"Year: 1995<br />yield:  1.5420<br />country: Brazil\",\"Year: 1996<br />yield:  1.8334<br />country: Brazil\",\"Year: 1997<br />yield:  1.6359<br />country: Brazil\",\"Year: 1998<br />yield:  1.6111<br />country: Brazil\",\"Year: 1999<br />yield:  1.9699<br />country: Brazil\",\"Year: 2000<br />yield:  1.5156<br />country: Brazil\",\"Year: 2001<br />yield:  1.9488<br />country: Brazil\",\"Year: 2002<br />yield:  1.4754<br />country: Brazil\",\"Year: 2003<br />yield:  2.4035<br />country: Brazil\",\"Year: 2004<br />yield:  2.0728<br />country: Brazil\",\"Year: 2005<br />yield:  1.9735<br />country: Brazil\",\"Year: 2006<br />yield:  1.5927<br />country: Brazil\",\"Year: 2007<br />yield:  2.2199<br />country: Brazil\",\"Year: 2008<br />yield:  2.5497<br />country: Brazil\",\"Year: 2009<br />yield:  2.0802<br />country: Brazil\",\"Year: 2010<br />yield:  2.8288<br />country: Brazil\",\"Year: 2011<br />yield:  2.6602<br />country: Brazil\",\"Year: 2012<br />yield:  2.3100<br />country: Brazil\",\"Year: 2013<br />yield:  2.7491<br />country: Brazil\",\"Year: 2014<br />yield:  2.2088<br />country: Brazil\",\"Year: 2015<br />yield:  2.2278<br />country: Brazil\",\"Year: 2016<br />yield:  3.1551<br />country: Brazil\",\"Year: 2017<br />yield:  2.2790<br />country: Brazil\",\"Year: 2018<br />yield:  2.6238<br />country: Brazil\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(83,180,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Brazil\",\"legendgroup\":\"Brazil\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.9538,2.1377,2.0868,2.7396,2.9665,3.5357,3.9284,3.6233,2.6316,3.2366,3.3545,3.3498,3.4034,3.4109,3.5935,2.5788,3.0748,2.7363,3.7518,3.4873,4.1277,3.6957,4.337,5.2135,5.9131,6.8865,7.121,7.3176,7.5288,8.1395,8.3916,8.4884,8.489,8.9381,9.1,9.4453,8.2417,9.4006,8.5153,9.412,9.4306,10.5902,9.9977,11.0678,11.2285,11.184,8.9302,10.1411,10.4956,11.0808,11.9978,10.7224,10.6321,10.1017,12.2904,11.544,11.2244,12.4706],\"text\":[\"Year: 1961<br />yield:  1.9538<br />country: Chile\",\"Year: 1962<br />yield:  2.1377<br />country: Chile\",\"Year: 1963<br />yield:  2.0868<br />country: Chile\",\"Year: 1964<br />yield:  2.7396<br />country: Chile\",\"Year: 1965<br />yield:  2.9665<br />country: Chile\",\"Year: 1966<br />yield:  3.5357<br />country: Chile\",\"Year: 1967<br />yield:  3.9284<br />country: Chile\",\"Year: 1968<br />yield:  3.6233<br />country: Chile\",\"Year: 1969<br />yield:  2.6316<br />country: Chile\",\"Year: 1970<br />yield:  3.2366<br />country: Chile\",\"Year: 1971<br />yield:  3.3545<br />country: Chile\",\"Year: 1972<br />yield:  3.3498<br />country: Chile\",\"Year: 1973<br />yield:  3.4034<br />country: Chile\",\"Year: 1974<br />yield:  3.4109<br />country: Chile\",\"Year: 1975<br />yield:  3.5935<br />country: Chile\",\"Year: 1976<br />yield:  2.5788<br />country: Chile\",\"Year: 1977<br />yield:  3.0748<br />country: Chile\",\"Year: 1978<br />yield:  2.7363<br />country: Chile\",\"Year: 1979<br />yield:  3.7518<br />country: Chile\",\"Year: 1980<br />yield:  3.4873<br />country: Chile\",\"Year: 1981<br />yield:  4.1277<br />country: Chile\",\"Year: 1982<br />yield:  3.6957<br />country: Chile\",\"Year: 1983<br />yield:  4.3370<br />country: Chile\",\"Year: 1984<br />yield:  5.2135<br />country: Chile\",\"Year: 1985<br />yield:  5.9131<br />country: Chile\",\"Year: 1986<br />yield:  6.8865<br />country: Chile\",\"Year: 1987<br />yield:  7.1210<br />country: Chile\",\"Year: 1988<br />yield:  7.3176<br />country: Chile\",\"Year: 1989<br />yield:  7.5288<br />country: Chile\",\"Year: 1990<br />yield:  8.1395<br />country: Chile\",\"Year: 1991<br />yield:  8.3916<br />country: Chile\",\"Year: 1992<br />yield:  8.4884<br />country: Chile\",\"Year: 1993<br />yield:  8.4890<br />country: Chile\",\"Year: 1994<br />yield:  8.9381<br />country: Chile\",\"Year: 1995<br />yield:  9.1000<br />country: Chile\",\"Year: 1996<br />yield:  9.4453<br />country: Chile\",\"Year: 1997<br />yield:  8.2417<br />country: Chile\",\"Year: 1998<br />yield:  9.4006<br />country: Chile\",\"Year: 1999<br />yield:  8.5153<br />country: Chile\",\"Year: 2000<br />yield:  9.4120<br />country: Chile\",\"Year: 2001<br />yield:  9.4306<br />country: Chile\",\"Year: 2002<br />yield: 10.5902<br />country: Chile\",\"Year: 2003<br />yield:  9.9977<br />country: Chile\",\"Year: 2004<br />yield: 11.0678<br />country: Chile\",\"Year: 2005<br />yield: 11.2285<br />country: Chile\",\"Year: 2006<br />yield: 11.1840<br />country: Chile\",\"Year: 2007<br />yield:  8.9302<br />country: Chile\",\"Year: 2008<br />yield: 10.1411<br />country: Chile\",\"Year: 2009<br />yield: 10.4956<br />country: Chile\",\"Year: 2010<br />yield: 11.0808<br />country: Chile\",\"Year: 2011<br />yield: 11.9978<br />country: Chile\",\"Year: 2012<br />yield: 10.7224<br />country: Chile\",\"Year: 2013<br />yield: 10.6321<br />country: Chile\",\"Year: 2014<br />yield: 10.1017<br />country: Chile\",\"Year: 2015<br />yield: 12.2904<br />country: Chile\",\"Year: 2016<br />yield: 11.5440<br />country: Chile\",\"Year: 2017<br />yield: 11.2244<br />country: Chile\",\"Year: 2018<br />yield: 12.4706<br />country: Chile\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,192,148,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Chile\",\"legendgroup\":\"Chile\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[8.7638,8.3717,9.5399,9.541,7.7219,10.5284,9.2938,9.0554,7.9053,9.5436,10.4449,9.2557,9.3505,10.8501,10.3164,7.8743,10.8128,10.7987,9.5204,10.175,11.2017,10.8713,10.179,12.7338,14.4528,15.0261,12.5985,14.9817,14.0645,15.03,14.2245,16.4033,14.5947,15.3807,15.22,13.89,16.4412,14.0485,16.4507,16.4821,19.1735,21.2397,19.5309,19.2104,20.06,22.0155,15.2389,17.2591,20.5101,21.2986,31.246,26.3269,23.3767,21.6752,19.0101,21.801,26.3762,28.6749],\"text\":[\"Year: 1961<br />yield:  8.7638<br />country: Chile\",\"Year: 1962<br />yield:  8.3717<br />country: Chile\",\"Year: 1963<br />yield:  9.5399<br />country: Chile\",\"Year: 1964<br />yield:  9.5410<br />country: Chile\",\"Year: 1965<br />yield:  7.7219<br />country: Chile\",\"Year: 1966<br />yield: 10.5284<br />country: Chile\",\"Year: 1967<br />yield:  9.2938<br />country: Chile\",\"Year: 1968<br />yield:  9.0554<br />country: Chile\",\"Year: 1969<br />yield:  7.9053<br />country: Chile\",\"Year: 1970<br />yield:  9.5436<br />country: Chile\",\"Year: 1971<br />yield: 10.4449<br />country: Chile\",\"Year: 1972<br />yield:  9.2557<br />country: Chile\",\"Year: 1973<br />yield:  9.3505<br />country: Chile\",\"Year: 1974<br />yield: 10.8501<br />country: Chile\",\"Year: 1975<br />yield: 10.3164<br />country: Chile\",\"Year: 1976<br />yield:  7.8743<br />country: Chile\",\"Year: 1977<br />yield: 10.8128<br />country: Chile\",\"Year: 1978<br />yield: 10.7987<br />country: Chile\",\"Year: 1979<br />yield:  9.5204<br />country: Chile\",\"Year: 1980<br />yield: 10.1750<br />country: Chile\",\"Year: 1981<br />yield: 11.2017<br />country: Chile\",\"Year: 1982<br />yield: 10.8713<br />country: Chile\",\"Year: 1983<br />yield: 10.1790<br />country: Chile\",\"Year: 1984<br />yield: 12.7338<br />country: Chile\",\"Year: 1985<br />yield: 14.4528<br />country: Chile\",\"Year: 1986<br />yield: 15.0261<br />country: Chile\",\"Year: 1987<br />yield: 12.5985<br />country: Chile\",\"Year: 1988<br />yield: 14.9817<br />country: Chile\",\"Year: 1989<br />yield: 14.0645<br />country: Chile\",\"Year: 1990<br />yield: 15.0300<br />country: Chile\",\"Year: 1991<br />yield: 14.2245<br />country: Chile\",\"Year: 1992<br />yield: 16.4033<br />country: Chile\",\"Year: 1993<br />yield: 14.5947<br />country: Chile\",\"Year: 1994<br />yield: 15.3807<br />country: Chile\",\"Year: 1995<br />yield: 15.2200<br />country: Chile\",\"Year: 1996<br />yield: 13.8900<br />country: Chile\",\"Year: 1997<br />yield: 16.4412<br />country: Chile\",\"Year: 1998<br />yield: 14.0485<br />country: Chile\",\"Year: 1999<br />yield: 16.4507<br />country: Chile\",\"Year: 2000<br />yield: 16.4821<br />country: Chile\",\"Year: 2001<br />yield: 19.1735<br />country: Chile\",\"Year: 2002<br />yield: 21.2397<br />country: Chile\",\"Year: 2003<br />yield: 19.5309<br />country: Chile\",\"Year: 2004<br />yield: 19.2104<br />country: Chile\",\"Year: 2005<br />yield: 20.0600<br />country: Chile\",\"Year: 2006<br />yield: 22.0155<br />country: Chile\",\"Year: 2007<br />yield: 15.2389<br />country: Chile\",\"Year: 2008<br />yield: 17.2591<br />country: Chile\",\"Year: 2009<br />yield: 20.5101<br />country: Chile\",\"Year: 2010<br />yield: 21.2986<br />country: Chile\",\"Year: 2011<br />yield: 31.2460<br />country: Chile\",\"Year: 2012<br />yield: 26.3269<br />country: Chile\",\"Year: 2013<br />yield: 23.3767<br />country: Chile\",\"Year: 2014<br />yield: 21.6752<br />country: Chile\",\"Year: 2015<br />yield: 19.0101<br />country: Chile\",\"Year: 2016<br />yield: 21.8010<br />country: Chile\",\"Year: 2017<br />yield: 26.3762<br />country: Chile\",\"Year: 2018<br />yield: 28.6749<br />country: Chile\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,192,148,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Chile\",\"legendgroup\":\"Chile\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[2.7207,2.8342,2.5695,2.6328,2.9114,2.0795,2.5455,2.8783,2.268,3.0228,2.4615,3.3574,2.964,2.4946,3.3383,3.4152,3.3844,3.2105,3.8489,2.3369,3.1764,3.5492,3.7976,4.1377,4.0667,3.9559,3.9451,4.171,4.3077,4.1734,3.9366,4.2044,4.4921,4.3834,4.3,4.7704,3.6336,3.9089,4.1508,5.2414,5.0179,5.0724,4.9893,4.7898,4.6677,5.7296,5.0663,5.792,5.3763,3.8599,5.1899,6.2435,6.2051,6.0221,6.8972,6.5564,6.1072,6.531],\"text\":[\"Year: 1961<br />yield:  2.7207<br />country: Chile\",\"Year: 1962<br />yield:  2.8342<br />country: Chile\",\"Year: 1963<br />yield:  2.5695<br />country: Chile\",\"Year: 1964<br />yield:  2.6328<br />country: Chile\",\"Year: 1965<br />yield:  2.9114<br />country: Chile\",\"Year: 1966<br />yield:  2.0795<br />country: Chile\",\"Year: 1967<br />yield:  2.5455<br />country: Chile\",\"Year: 1968<br />yield:  2.8783<br />country: Chile\",\"Year: 1969<br />yield:  2.2680<br />country: Chile\",\"Year: 1970<br />yield:  3.0228<br />country: Chile\",\"Year: 1971<br />yield:  2.4615<br />country: Chile\",\"Year: 1972<br />yield:  3.3574<br />country: Chile\",\"Year: 1973<br />yield:  2.9640<br />country: Chile\",\"Year: 1974<br />yield:  2.4946<br />country: Chile\",\"Year: 1975<br />yield:  3.3383<br />country: Chile\",\"Year: 1976<br />yield:  3.4152<br />country: Chile\",\"Year: 1977<br />yield:  3.3844<br />country: Chile\",\"Year: 1978<br />yield:  3.2105<br />country: Chile\",\"Year: 1979<br />yield:  3.8489<br />country: Chile\",\"Year: 1980<br />yield:  2.3369<br />country: Chile\",\"Year: 1981<br />yield:  3.1764<br />country: Chile\",\"Year: 1982<br />yield:  3.5492<br />country: Chile\",\"Year: 1983<br />yield:  3.7976<br />country: Chile\",\"Year: 1984<br />yield:  4.1377<br />country: Chile\",\"Year: 1985<br />yield:  4.0667<br />country: Chile\",\"Year: 1986<br />yield:  3.9559<br />country: Chile\",\"Year: 1987<br />yield:  3.9451<br />country: Chile\",\"Year: 1988<br />yield:  4.1710<br />country: Chile\",\"Year: 1989<br />yield:  4.3077<br />country: Chile\",\"Year: 1990<br />yield:  4.1734<br />country: Chile\",\"Year: 1991<br />yield:  3.9366<br />country: Chile\",\"Year: 1992<br />yield:  4.2044<br />country: Chile\",\"Year: 1993<br />yield:  4.4921<br />country: Chile\",\"Year: 1994<br />yield:  4.3834<br />country: Chile\",\"Year: 1995<br />yield:  4.3000<br />country: Chile\",\"Year: 1996<br />yield:  4.7704<br />country: Chile\",\"Year: 1997<br />yield:  3.6336<br />country: Chile\",\"Year: 1998<br />yield:  3.9089<br />country: Chile\",\"Year: 1999<br />yield:  4.1508<br />country: Chile\",\"Year: 2000<br />yield:  5.2414<br />country: Chile\",\"Year: 2001<br />yield:  5.0179<br />country: Chile\",\"Year: 2002<br />yield:  5.0724<br />country: Chile\",\"Year: 2003<br />yield:  4.9893<br />country: Chile\",\"Year: 2004<br />yield:  4.7898<br />country: Chile\",\"Year: 2005<br />yield:  4.6677<br />country: Chile\",\"Year: 2006<br />yield:  5.7296<br />country: Chile\",\"Year: 2007<br />yield:  5.0663<br />country: Chile\",\"Year: 2008<br />yield:  5.7920<br />country: Chile\",\"Year: 2009<br />yield:  5.3763<br />country: Chile\",\"Year: 2010<br />yield:  3.8599<br />country: Chile\",\"Year: 2011<br />yield:  5.1899<br />country: Chile\",\"Year: 2012<br />yield:  6.2435<br />country: Chile\",\"Year: 2013<br />yield:  6.2051<br />country: Chile\",\"Year: 2014<br />yield:  6.0221<br />country: Chile\",\"Year: 2015<br />yield:  6.8972<br />country: Chile\",\"Year: 2016<br />yield:  6.5564<br />country: Chile\",\"Year: 2017<br />yield:  6.1072<br />country: Chile\",\"Year: 2018<br />yield:  6.5310<br />country: Chile\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,192,148,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Chile\",\"legendgroup\":\"Chile\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.3398,1.2614,1.5121,1.5489,1.5347,1.7262,1.675,1.742,1.6341,1.7654,1.8805,1.679,1.3988,1.6445,1.4618,1.2421,1.9416,1.5401,1.7755,1.7701,1.5873,1.7394,1.6314,2.0968,2.3009,2.8565,2.7701,3.0075,3.2677,2.9481,3.4057,3.3787,3.35,3.5157,3.55,3.3278,4.0174,4.3846,3.5342,3.812,4.2999,4.2722,4.323,4.571,4.413,4.4601,4.7859,4.5748,4.0809,5.7658,5.806,4.9468,5.8143,5.329,5.6326,6.0706,5.9966,6.2137],\"text\":[\"Year: 1961<br />yield:  1.3398<br />country: Chile\",\"Year: 1962<br />yield:  1.2614<br />country: Chile\",\"Year: 1963<br />yield:  1.5121<br />country: Chile\",\"Year: 1964<br />yield:  1.5489<br />country: Chile\",\"Year: 1965<br />yield:  1.5347<br />country: Chile\",\"Year: 1966<br />yield:  1.7262<br />country: Chile\",\"Year: 1967<br />yield:  1.6750<br />country: Chile\",\"Year: 1968<br />yield:  1.7420<br />country: Chile\",\"Year: 1969<br />yield:  1.6341<br />country: Chile\",\"Year: 1970<br />yield:  1.7654<br />country: Chile\",\"Year: 1971<br />yield:  1.8805<br />country: Chile\",\"Year: 1972<br />yield:  1.6790<br />country: Chile\",\"Year: 1973<br />yield:  1.3988<br />country: Chile\",\"Year: 1974<br />yield:  1.6445<br />country: Chile\",\"Year: 1975<br />yield:  1.4618<br />country: Chile\",\"Year: 1976<br />yield:  1.2421<br />country: Chile\",\"Year: 1977<br />yield:  1.9416<br />country: Chile\",\"Year: 1978<br />yield:  1.5401<br />country: Chile\",\"Year: 1979<br />yield:  1.7755<br />country: Chile\",\"Year: 1980<br />yield:  1.7701<br />country: Chile\",\"Year: 1981<br />yield:  1.5873<br />country: Chile\",\"Year: 1982<br />yield:  1.7394<br />country: Chile\",\"Year: 1983<br />yield:  1.6314<br />country: Chile\",\"Year: 1984<br />yield:  2.0968<br />country: Chile\",\"Year: 1985<br />yield:  2.3009<br />country: Chile\",\"Year: 1986<br />yield:  2.8565<br />country: Chile\",\"Year: 1987<br />yield:  2.7701<br />country: Chile\",\"Year: 1988<br />yield:  3.0075<br />country: Chile\",\"Year: 1989<br />yield:  3.2677<br />country: Chile\",\"Year: 1990<br />yield:  2.9481<br />country: Chile\",\"Year: 1991<br />yield:  3.4057<br />country: Chile\",\"Year: 1992<br />yield:  3.3787<br />country: Chile\",\"Year: 1993<br />yield:  3.3500<br />country: Chile\",\"Year: 1994<br />yield:  3.5157<br />country: Chile\",\"Year: 1995<br />yield:  3.5500<br />country: Chile\",\"Year: 1996<br />yield:  3.3278<br />country: Chile\",\"Year: 1997<br />yield:  4.0174<br />country: Chile\",\"Year: 1998<br />yield:  4.3846<br />country: Chile\",\"Year: 1999<br />yield:  3.5342<br />country: Chile\",\"Year: 2000<br />yield:  3.8120<br />country: Chile\",\"Year: 2001<br />yield:  4.2999<br />country: Chile\",\"Year: 2002<br />yield:  4.2722<br />country: Chile\",\"Year: 2003<br />yield:  4.3230<br />country: Chile\",\"Year: 2004<br />yield:  4.5710<br />country: Chile\",\"Year: 2005<br />yield:  4.4130<br />country: Chile\",\"Year: 2006<br />yield:  4.4601<br />country: Chile\",\"Year: 2007<br />yield:  4.7859<br />country: Chile\",\"Year: 2008<br />yield:  4.5748<br />country: Chile\",\"Year: 2009<br />yield:  4.0809<br />country: Chile\",\"Year: 2010<br />yield:  5.7658<br />country: Chile\",\"Year: 2011<br />yield:  5.8060<br />country: Chile\",\"Year: 2012<br />yield:  4.9468<br />country: Chile\",\"Year: 2013<br />yield:  5.8143<br />country: Chile\",\"Year: 2014<br />yield:  5.3290<br />country: Chile\",\"Year: 2015<br />yield:  5.6326<br />country: Chile\",\"Year: 2016<br />yield:  6.0706<br />country: Chile\",\"Year: 2017<br />yield:  5.9966<br />country: Chile\",\"Year: 2018<br />yield:  6.2137<br />country: Chile\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,192,148,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Chile\",\"legendgroup\":\"Chile\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.2009,1.3,1.25,1.2972,1.3003,1.0997,1.3,1,1.2,1.3174,1.2125,1.135,1.3254,1.3663,1.3511,1.3659,1.3918,1.3023,1.5044,1.5531,1.6103,1.4892,1.5412,1.4345,1.6987,1.7013,1.8046,1.902,1.9889,2.1991,1.6502,1.743,1.763,2.114,2.466,2.015,2.7483,2.4575,2.2917,1.9512,2.3308,2.3442,2.3849,2.5455,2.075,2.6829,2.77,2.8804,2.4,3.9152,3.9198,3.095,4,4,5.2483,5.367,5.485,4.995],\"text\":[\"Year: 1961<br />yield:  1.2009<br />country: Paraguay\",\"Year: 1962<br />yield:  1.3000<br />country: Paraguay\",\"Year: 1963<br />yield:  1.2500<br />country: Paraguay\",\"Year: 1964<br />yield:  1.2972<br />country: Paraguay\",\"Year: 1965<br />yield:  1.3003<br />country: Paraguay\",\"Year: 1966<br />yield:  1.0997<br />country: Paraguay\",\"Year: 1967<br />yield:  1.3000<br />country: Paraguay\",\"Year: 1968<br />yield:  1.0000<br />country: Paraguay\",\"Year: 1969<br />yield:  1.2000<br />country: Paraguay\",\"Year: 1970<br />yield:  1.3174<br />country: Paraguay\",\"Year: 1971<br />yield:  1.2125<br />country: Paraguay\",\"Year: 1972<br />yield:  1.1350<br />country: Paraguay\",\"Year: 1973<br />yield:  1.3254<br />country: Paraguay\",\"Year: 1974<br />yield:  1.3663<br />country: Paraguay\",\"Year: 1975<br />yield:  1.3511<br />country: Paraguay\",\"Year: 1976<br />yield:  1.3659<br />country: Paraguay\",\"Year: 1977<br />yield:  1.3918<br />country: Paraguay\",\"Year: 1978<br />yield:  1.3023<br />country: Paraguay\",\"Year: 1979<br />yield:  1.5044<br />country: Paraguay\",\"Year: 1980<br />yield:  1.5531<br />country: Paraguay\",\"Year: 1981<br />yield:  1.6103<br />country: Paraguay\",\"Year: 1982<br />yield:  1.4892<br />country: Paraguay\",\"Year: 1983<br />yield:  1.5412<br />country: Paraguay\",\"Year: 1984<br />yield:  1.4345<br />country: Paraguay\",\"Year: 1985<br />yield:  1.6987<br />country: Paraguay\",\"Year: 1986<br />yield:  1.7013<br />country: Paraguay\",\"Year: 1987<br />yield:  1.8046<br />country: Paraguay\",\"Year: 1988<br />yield:  1.9020<br />country: Paraguay\",\"Year: 1989<br />yield:  1.9889<br />country: Paraguay\",\"Year: 1990<br />yield:  2.1991<br />country: Paraguay\",\"Year: 1991<br />yield:  1.6502<br />country: Paraguay\",\"Year: 1992<br />yield:  1.7430<br />country: Paraguay\",\"Year: 1993<br />yield:  1.7630<br />country: Paraguay\",\"Year: 1994<br />yield:  2.1140<br />country: Paraguay\",\"Year: 1995<br />yield:  2.4660<br />country: Paraguay\",\"Year: 1996<br />yield:  2.0150<br />country: Paraguay\",\"Year: 1997<br />yield:  2.7483<br />country: Paraguay\",\"Year: 1998<br />yield:  2.4575<br />country: Paraguay\",\"Year: 1999<br />yield:  2.2917<br />country: Paraguay\",\"Year: 2000<br />yield:  1.9512<br />country: Paraguay\",\"Year: 2001<br />yield:  2.3308<br />country: Paraguay\",\"Year: 2002<br />yield:  2.3442<br />country: Paraguay\",\"Year: 2003<br />yield:  2.3849<br />country: Paraguay\",\"Year: 2004<br />yield:  2.5455<br />country: Paraguay\",\"Year: 2005<br />yield:  2.0750<br />country: Paraguay\",\"Year: 2006<br />yield:  2.6829<br />country: Paraguay\",\"Year: 2007<br />yield:  2.7700<br />country: Paraguay\",\"Year: 2008<br />yield:  2.8804<br />country: Paraguay\",\"Year: 2009<br />yield:  2.4000<br />country: Paraguay\",\"Year: 2010<br />yield:  3.9152<br />country: Paraguay\",\"Year: 2011<br />yield:  3.9198<br />country: Paraguay\",\"Year: 2012<br />yield:  3.0950<br />country: Paraguay\",\"Year: 2013<br />yield:  4.0000<br />country: Paraguay\",\"Year: 2014<br />yield:  4.0000<br />country: Paraguay\",\"Year: 2015<br />yield:  5.2483<br />country: Paraguay\",\"Year: 2016<br />yield:  5.3670<br />country: Paraguay\",\"Year: 2017<br />yield:  5.4850<br />country: Paraguay\",\"Year: 2018<br />yield:  4.9950<br />country: Paraguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,182,235,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Paraguay\",\"legendgroup\":\"Paraguay\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[3.25,3.3333,4,4,4,5,7.5385,7.8295,7.898,3.077,4.3333,5.875,6.2,6.6153,7.2279,8.0275,8.3197,8.624,8.828,3.1357,3.861,5.1705,5.9184,6.715,6.92,6.225,6.525,7.6786,7.205,6.7,4.984,5.5972,5.5972,5.9377,6.0102,6.1267,6.1794,6.1921,5.9957,5.2727,5.4257,5.602,6.4,6.329,6.2353,6.4737,6.5,6.4578,5.05,13.1165,15.2174,12,14.7679,15,14.4504,14.5,14.4615,14.4774],\"text\":[\"Year: 1961<br />yield:  3.2500<br />country: Paraguay\",\"Year: 1962<br />yield:  3.3333<br />country: Paraguay\",\"Year: 1963<br />yield:  4.0000<br />country: Paraguay\",\"Year: 1964<br />yield:  4.0000<br />country: Paraguay\",\"Year: 1965<br />yield:  4.0000<br />country: Paraguay\",\"Year: 1966<br />yield:  5.0000<br />country: Paraguay\",\"Year: 1967<br />yield:  7.5385<br />country: Paraguay\",\"Year: 1968<br />yield:  7.8295<br />country: Paraguay\",\"Year: 1969<br />yield:  7.8980<br />country: Paraguay\",\"Year: 1970<br />yield:  3.0770<br />country: Paraguay\",\"Year: 1971<br />yield:  4.3333<br />country: Paraguay\",\"Year: 1972<br />yield:  5.8750<br />country: Paraguay\",\"Year: 1973<br />yield:  6.2000<br />country: Paraguay\",\"Year: 1974<br />yield:  6.6153<br />country: Paraguay\",\"Year: 1975<br />yield:  7.2279<br />country: Paraguay\",\"Year: 1976<br />yield:  8.0275<br />country: Paraguay\",\"Year: 1977<br />yield:  8.3197<br />country: Paraguay\",\"Year: 1978<br />yield:  8.6240<br />country: Paraguay\",\"Year: 1979<br />yield:  8.8280<br />country: Paraguay\",\"Year: 1980<br />yield:  3.1357<br />country: Paraguay\",\"Year: 1981<br />yield:  3.8610<br />country: Paraguay\",\"Year: 1982<br />yield:  5.1705<br />country: Paraguay\",\"Year: 1983<br />yield:  5.9184<br />country: Paraguay\",\"Year: 1984<br />yield:  6.7150<br />country: Paraguay\",\"Year: 1985<br />yield:  6.9200<br />country: Paraguay\",\"Year: 1986<br />yield:  6.2250<br />country: Paraguay\",\"Year: 1987<br />yield:  6.5250<br />country: Paraguay\",\"Year: 1988<br />yield:  7.6786<br />country: Paraguay\",\"Year: 1989<br />yield:  7.2050<br />country: Paraguay\",\"Year: 1990<br />yield:  6.7000<br />country: Paraguay\",\"Year: 1991<br />yield:  4.9840<br />country: Paraguay\",\"Year: 1992<br />yield:  5.5972<br />country: Paraguay\",\"Year: 1993<br />yield:  5.5972<br />country: Paraguay\",\"Year: 1994<br />yield:  5.9377<br />country: Paraguay\",\"Year: 1995<br />yield:  6.0102<br />country: Paraguay\",\"Year: 1996<br />yield:  6.1267<br />country: Paraguay\",\"Year: 1997<br />yield:  6.1794<br />country: Paraguay\",\"Year: 1998<br />yield:  6.1921<br />country: Paraguay\",\"Year: 1999<br />yield:  5.9957<br />country: Paraguay\",\"Year: 2000<br />yield:  5.2727<br />country: Paraguay\",\"Year: 2001<br />yield:  5.4257<br />country: Paraguay\",\"Year: 2002<br />yield:  5.6020<br />country: Paraguay\",\"Year: 2003<br />yield:  6.4000<br />country: Paraguay\",\"Year: 2004<br />yield:  6.3290<br />country: Paraguay\",\"Year: 2005<br />yield:  6.2353<br />country: Paraguay\",\"Year: 2006<br />yield:  6.4737<br />country: Paraguay\",\"Year: 2007<br />yield:  6.5000<br />country: Paraguay\",\"Year: 2008<br />yield:  6.4578<br />country: Paraguay\",\"Year: 2009<br />yield:  5.0500<br />country: Paraguay\",\"Year: 2010<br />yield: 13.1165<br />country: Paraguay\",\"Year: 2011<br />yield: 15.2174<br />country: Paraguay\",\"Year: 2012<br />yield: 12.0000<br />country: Paraguay\",\"Year: 2013<br />yield: 14.7679<br />country: Paraguay\",\"Year: 2014<br />yield: 15.0000<br />country: Paraguay\",\"Year: 2015<br />yield: 14.4504<br />country: Paraguay\",\"Year: 2016<br />yield: 14.5000<br />country: Paraguay\",\"Year: 2017<br />yield: 14.4615<br />country: Paraguay\",\"Year: 2018<br />yield: 14.4774<br />country: Paraguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,182,235,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Paraguay\",\"legendgroup\":\"Paraguay\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[2.2,2.4,2.2857,2.5,2.7,2.1957,2.4959,2.2286,2.6557,1.9661,2.0793,1.7963,1.9413,2.2134,2.2711,2.0195,2.044,1.8312,1.8902,1.7,1.9064,2.0096,2.1428,2.1836,2.4925,2.0066,2.5731,2.4369,2.6996,2.5206,3.1698,3.8317,3.7715,3.9785,4.1143,3.6692,3.6988,3.8792,4.6126,3.8492,3.9797,3.8841,3.6383,4.0323,3.0448,3,3.0952,4.272,4.3,5.2998,5.1936,4.95,6.3,6.7,6.7013,6.6,6.6,6.3],\"text\":[\"Year: 1961<br />yield:  2.2000<br />country: Paraguay\",\"Year: 1962<br />yield:  2.4000<br />country: Paraguay\",\"Year: 1963<br />yield:  2.2857<br />country: Paraguay\",\"Year: 1964<br />yield:  2.5000<br />country: Paraguay\",\"Year: 1965<br />yield:  2.7000<br />country: Paraguay\",\"Year: 1966<br />yield:  2.1957<br />country: Paraguay\",\"Year: 1967<br />yield:  2.4959<br />country: Paraguay\",\"Year: 1968<br />yield:  2.2286<br />country: Paraguay\",\"Year: 1969<br />yield:  2.6557<br />country: Paraguay\",\"Year: 1970<br />yield:  1.9661<br />country: Paraguay\",\"Year: 1971<br />yield:  2.0793<br />country: Paraguay\",\"Year: 1972<br />yield:  1.7963<br />country: Paraguay\",\"Year: 1973<br />yield:  1.9413<br />country: Paraguay\",\"Year: 1974<br />yield:  2.2134<br />country: Paraguay\",\"Year: 1975<br />yield:  2.2711<br />country: Paraguay\",\"Year: 1976<br />yield:  2.0195<br />country: Paraguay\",\"Year: 1977<br />yield:  2.0440<br />country: Paraguay\",\"Year: 1978<br />yield:  1.8312<br />country: Paraguay\",\"Year: 1979<br />yield:  1.8902<br />country: Paraguay\",\"Year: 1980<br />yield:  1.7000<br />country: Paraguay\",\"Year: 1981<br />yield:  1.9064<br />country: Paraguay\",\"Year: 1982<br />yield:  2.0096<br />country: Paraguay\",\"Year: 1983<br />yield:  2.1428<br />country: Paraguay\",\"Year: 1984<br />yield:  2.1836<br />country: Paraguay\",\"Year: 1985<br />yield:  2.4925<br />country: Paraguay\",\"Year: 1986<br />yield:  2.0066<br />country: Paraguay\",\"Year: 1987<br />yield:  2.5731<br />country: Paraguay\",\"Year: 1988<br />yield:  2.4369<br />country: Paraguay\",\"Year: 1989<br />yield:  2.6996<br />country: Paraguay\",\"Year: 1990<br />yield:  2.5206<br />country: Paraguay\",\"Year: 1991<br />yield:  3.1698<br />country: Paraguay\",\"Year: 1992<br />yield:  3.8317<br />country: Paraguay\",\"Year: 1993<br />yield:  3.7715<br />country: Paraguay\",\"Year: 1994<br />yield:  3.9785<br />country: Paraguay\",\"Year: 1995<br />yield:  4.1143<br />country: Paraguay\",\"Year: 1996<br />yield:  3.6692<br />country: Paraguay\",\"Year: 1997<br />yield:  3.6988<br />country: Paraguay\",\"Year: 1998<br />yield:  3.8792<br />country: Paraguay\",\"Year: 1999<br />yield:  4.6126<br />country: Paraguay\",\"Year: 2000<br />yield:  3.8492<br />country: Paraguay\",\"Year: 2001<br />yield:  3.9797<br />country: Paraguay\",\"Year: 2002<br />yield:  3.8841<br />country: Paraguay\",\"Year: 2003<br />yield:  3.6383<br />country: Paraguay\",\"Year: 2004<br />yield:  4.0323<br />country: Paraguay\",\"Year: 2005<br />yield:  3.0448<br />country: Paraguay\",\"Year: 2006<br />yield:  3.0000<br />country: Paraguay\",\"Year: 2007<br />yield:  3.0952<br />country: Paraguay\",\"Year: 2008<br />yield:  4.2720<br />country: Paraguay\",\"Year: 2009<br />yield:  4.3000<br />country: Paraguay\",\"Year: 2010<br />yield:  5.2998<br />country: Paraguay\",\"Year: 2011<br />yield:  5.1936<br />country: Paraguay\",\"Year: 2012<br />yield:  4.9500<br />country: Paraguay\",\"Year: 2013<br />yield:  6.3000<br />country: Paraguay\",\"Year: 2014<br />yield:  6.7000<br />country: Paraguay\",\"Year: 2015<br />yield:  6.7013<br />country: Paraguay\",\"Year: 2016<br />yield:  6.6000<br />country: Paraguay\",\"Year: 2017<br />yield:  6.6000<br />country: Paraguay\",\"Year: 2018<br />yield:  6.3000<br />country: Paraguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,182,235,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Paraguay\",\"legendgroup\":\"Paraguay\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[0.9,0.7,0.9072,0.6481,1,1.1,1.201,1.0133,0.9141,0.7333,1.0641,0.5466,1.133,1.1632,0.7092,1.2087,0.9813,1.2,1.2394,1.7008,1.2377,1.3157,1.2016,1.2004,1.5998,1.5996,2.0971,1.8992,1.4977,1.6571,1.5636,1.6571,2.2131,2.1494,1.2094,2.4544,1.7862,1.1419,0.9584,1.8101,1.8334,1.7263,2.2,2.2,2.1918,1.6986,2.5,2.0986,2.1,2.5,2.5049,2.601,2.6,1.5,1.8986,2.2,2,1.68],\"text\":[\"Year: 1961<br />yield:  0.9000<br />country: Paraguay\",\"Year: 1962<br />yield:  0.7000<br />country: Paraguay\",\"Year: 1963<br />yield:  0.9072<br />country: Paraguay\",\"Year: 1964<br />yield:  0.6481<br />country: Paraguay\",\"Year: 1965<br />yield:  1.0000<br />country: Paraguay\",\"Year: 1966<br />yield:  1.1000<br />country: Paraguay\",\"Year: 1967<br />yield:  1.2010<br />country: Paraguay\",\"Year: 1968<br />yield:  1.0133<br />country: Paraguay\",\"Year: 1969<br />yield:  0.9141<br />country: Paraguay\",\"Year: 1970<br />yield:  0.7333<br />country: Paraguay\",\"Year: 1971<br />yield:  1.0641<br />country: Paraguay\",\"Year: 1972<br />yield:  0.5466<br />country: Paraguay\",\"Year: 1973<br />yield:  1.1330<br />country: Paraguay\",\"Year: 1974<br />yield:  1.1632<br />country: Paraguay\",\"Year: 1975<br />yield:  0.7092<br />country: Paraguay\",\"Year: 1976<br />yield:  1.2087<br />country: Paraguay\",\"Year: 1977<br />yield:  0.9813<br />country: Paraguay\",\"Year: 1978<br />yield:  1.2000<br />country: Paraguay\",\"Year: 1979<br />yield:  1.2394<br />country: Paraguay\",\"Year: 1980<br />yield:  1.7008<br />country: Paraguay\",\"Year: 1981<br />yield:  1.2377<br />country: Paraguay\",\"Year: 1982<br />yield:  1.3157<br />country: Paraguay\",\"Year: 1983<br />yield:  1.2016<br />country: Paraguay\",\"Year: 1984<br />yield:  1.2004<br />country: Paraguay\",\"Year: 1985<br />yield:  1.5998<br />country: Paraguay\",\"Year: 1986<br />yield:  1.5996<br />country: Paraguay\",\"Year: 1987<br />yield:  2.0971<br />country: Paraguay\",\"Year: 1988<br />yield:  1.8992<br />country: Paraguay\",\"Year: 1989<br />yield:  1.4977<br />country: Paraguay\",\"Year: 1990<br />yield:  1.6571<br />country: Paraguay\",\"Year: 1991<br />yield:  1.5636<br />country: Paraguay\",\"Year: 1992<br />yield:  1.6571<br />country: Paraguay\",\"Year: 1993<br />yield:  2.2131<br />country: Paraguay\",\"Year: 1994<br />yield:  2.1494<br />country: Paraguay\",\"Year: 1995<br />yield:  1.2094<br />country: Paraguay\",\"Year: 1996<br />yield:  2.4544<br />country: Paraguay\",\"Year: 1997<br />yield:  1.7862<br />country: Paraguay\",\"Year: 1998<br />yield:  1.1419<br />country: Paraguay\",\"Year: 1999<br />yield:  0.9584<br />country: Paraguay\",\"Year: 2000<br />yield:  1.8101<br />country: Paraguay\",\"Year: 2001<br />yield:  1.8334<br />country: Paraguay\",\"Year: 2002<br />yield:  1.7263<br />country: Paraguay\",\"Year: 2003<br />yield:  2.2000<br />country: Paraguay\",\"Year: 2004<br />yield:  2.2000<br />country: Paraguay\",\"Year: 2005<br />yield:  2.1918<br />country: Paraguay\",\"Year: 2006<br />yield:  1.6986<br />country: Paraguay\",\"Year: 2007<br />yield:  2.5000<br />country: Paraguay\",\"Year: 2008<br />yield:  2.0986<br />country: Paraguay\",\"Year: 2009<br />yield:  2.1000<br />country: Paraguay\",\"Year: 2010<br />yield:  2.5000<br />country: Paraguay\",\"Year: 2011<br />yield:  2.5049<br />country: Paraguay\",\"Year: 2012<br />yield:  2.6010<br />country: Paraguay\",\"Year: 2013<br />yield:  2.6000<br />country: Paraguay\",\"Year: 2014<br />yield:  1.5000<br />country: Paraguay\",\"Year: 2015<br />yield:  1.8986<br />country: Paraguay\",\"Year: 2016<br />yield:  2.2000<br />country: Paraguay\",\"Year: 2017<br />yield:  2.0000<br />country: Paraguay\",\"Year: 2018<br />yield:  1.6800<br />country: Paraguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(0,182,235,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Paraguay\",\"legendgroup\":\"Paraguay\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.3419,1.3027,1.3281,1.4486,1.6275,1.637,1.6296,1.69,1.6007,1.6085,1.6487,1.6408,1.6348,1.6635,1.7506,1.8827,1.8772,1.6814,1.6749,1.5823,1.7307,1.7418,1.6977,1.9777,1.8944,2.041,2.0045,1.9617,2.0851,1.9532,1.9213,1.8858,2.1634,2.0891,1.9593,2.5267,2.0008,2.1121,2.3053,2.4119,2.5887,2.6708,2.7782,2.6734,2.6289,2.7129,2.8371,2.9673,3.029,3.0999,3.1866,3.3084,3.2686,3.1601,3.3988,3.2477,3.4126,3.4416],\"text\":[\"Year: 1961<br />yield:  1.3419<br />country: Peru\",\"Year: 1962<br />yield:  1.3027<br />country: Peru\",\"Year: 1963<br />yield:  1.3281<br />country: Peru\",\"Year: 1964<br />yield:  1.4486<br />country: Peru\",\"Year: 1965<br />yield:  1.6275<br />country: Peru\",\"Year: 1966<br />yield:  1.6370<br />country: Peru\",\"Year: 1967<br />yield:  1.6296<br />country: Peru\",\"Year: 1968<br />yield:  1.6900<br />country: Peru\",\"Year: 1969<br />yield:  1.6007<br />country: Peru\",\"Year: 1970<br />yield:  1.6085<br />country: Peru\",\"Year: 1971<br />yield:  1.6487<br />country: Peru\",\"Year: 1972<br />yield:  1.6408<br />country: Peru\",\"Year: 1973<br />yield:  1.6348<br />country: Peru\",\"Year: 1974<br />yield:  1.6635<br />country: Peru\",\"Year: 1975<br />yield:  1.7506<br />country: Peru\",\"Year: 1976<br />yield:  1.8827<br />country: Peru\",\"Year: 1977<br />yield:  1.8772<br />country: Peru\",\"Year: 1978<br />yield:  1.6814<br />country: Peru\",\"Year: 1979<br />yield:  1.6749<br />country: Peru\",\"Year: 1980<br />yield:  1.5823<br />country: Peru\",\"Year: 1981<br />yield:  1.7307<br />country: Peru\",\"Year: 1982<br />yield:  1.7418<br />country: Peru\",\"Year: 1983<br />yield:  1.6977<br />country: Peru\",\"Year: 1984<br />yield:  1.9777<br />country: Peru\",\"Year: 1985<br />yield:  1.8944<br />country: Peru\",\"Year: 1986<br />yield:  2.0410<br />country: Peru\",\"Year: 1987<br />yield:  2.0045<br />country: Peru\",\"Year: 1988<br />yield:  1.9617<br />country: Peru\",\"Year: 1989<br />yield:  2.0851<br />country: Peru\",\"Year: 1990<br />yield:  1.9532<br />country: Peru\",\"Year: 1991<br />yield:  1.9213<br />country: Peru\",\"Year: 1992<br />yield:  1.8858<br />country: Peru\",\"Year: 1993<br />yield:  2.1634<br />country: Peru\",\"Year: 1994<br />yield:  2.0891<br />country: Peru\",\"Year: 1995<br />yield:  1.9593<br />country: Peru\",\"Year: 1996<br />yield:  2.5267<br />country: Peru\",\"Year: 1997<br />yield:  2.0008<br />country: Peru\",\"Year: 1998<br />yield:  2.1121<br />country: Peru\",\"Year: 1999<br />yield:  2.3053<br />country: Peru\",\"Year: 2000<br />yield:  2.4119<br />country: Peru\",\"Year: 2001<br />yield:  2.5887<br />country: Peru\",\"Year: 2002<br />yield:  2.6708<br />country: Peru\",\"Year: 2003<br />yield:  2.7782<br />country: Peru\",\"Year: 2004<br />yield:  2.6734<br />country: Peru\",\"Year: 2005<br />yield:  2.6289<br />country: Peru\",\"Year: 2006<br />yield:  2.7129<br />country: Peru\",\"Year: 2007<br />yield:  2.8371<br />country: Peru\",\"Year: 2008<br />yield:  2.9673<br />country: Peru\",\"Year: 2009<br />yield:  3.0290<br />country: Peru\",\"Year: 2010<br />yield:  3.0999<br />country: Peru\",\"Year: 2011<br />yield:  3.1866<br />country: Peru\",\"Year: 2012<br />yield:  3.3084<br />country: Peru\",\"Year: 2013<br />yield:  3.2686<br />country: Peru\",\"Year: 2014<br />yield:  3.1601<br />country: Peru\",\"Year: 2015<br />yield:  3.3988<br />country: Peru\",\"Year: 2016<br />yield:  3.2477<br />country: Peru\",\"Year: 2017<br />yield:  3.4126<br />country: Peru\",\"Year: 2018<br />yield:  3.4416<br />country: Peru\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(165,138,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Peru\",\"legendgroup\":\"Peru\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[5.2875,5.3635,5.1727,5.8552,6.245,5.8867,6.2956,6.0843,6.1135,6.0287,7.2632,6.324,6.3997,6.4287,6.5395,6.5939,6.545,6.8584,7.0045,7.1969,8.1801,7.7795,7.6047,8.2911,8.3864,8.625,8.036,8.9243,8.7904,7.8805,7.9465,7.4276,8.392,9.3738,9.7817,10.0629,9.6703,9.7887,11.2513,11.504,11.4862,12.1751,12.1854,12.1901,12.4584,12.4533,12.6342,12.9138,13.3353,13.1588,13.7379,14.3316,14.4125,14.7779,14.9122,14.5293,15.3875,15.8503],\"text\":[\"Year: 1961<br />yield:  5.2875<br />country: Peru\",\"Year: 1962<br />yield:  5.3635<br />country: Peru\",\"Year: 1963<br />yield:  5.1727<br />country: Peru\",\"Year: 1964<br />yield:  5.8552<br />country: Peru\",\"Year: 1965<br />yield:  6.2450<br />country: Peru\",\"Year: 1966<br />yield:  5.8867<br />country: Peru\",\"Year: 1967<br />yield:  6.2956<br />country: Peru\",\"Year: 1968<br />yield:  6.0843<br />country: Peru\",\"Year: 1969<br />yield:  6.1135<br />country: Peru\",\"Year: 1970<br />yield:  6.0287<br />country: Peru\",\"Year: 1971<br />yield:  7.2632<br />country: Peru\",\"Year: 1972<br />yield:  6.3240<br />country: Peru\",\"Year: 1973<br />yield:  6.3997<br />country: Peru\",\"Year: 1974<br />yield:  6.4287<br />country: Peru\",\"Year: 1975<br />yield:  6.5395<br />country: Peru\",\"Year: 1976<br />yield:  6.5939<br />country: Peru\",\"Year: 1977<br />yield:  6.5450<br />country: Peru\",\"Year: 1978<br />yield:  6.8584<br />country: Peru\",\"Year: 1979<br />yield:  7.0045<br />country: Peru\",\"Year: 1980<br />yield:  7.1969<br />country: Peru\",\"Year: 1981<br />yield:  8.1801<br />country: Peru\",\"Year: 1982<br />yield:  7.7795<br />country: Peru\",\"Year: 1983<br />yield:  7.6047<br />country: Peru\",\"Year: 1984<br />yield:  8.2911<br />country: Peru\",\"Year: 1985<br />yield:  8.3864<br />country: Peru\",\"Year: 1986<br />yield:  8.6250<br />country: Peru\",\"Year: 1987<br />yield:  8.0360<br />country: Peru\",\"Year: 1988<br />yield:  8.9243<br />country: Peru\",\"Year: 1989<br />yield:  8.7904<br />country: Peru\",\"Year: 1990<br />yield:  7.8805<br />country: Peru\",\"Year: 1991<br />yield:  7.9465<br />country: Peru\",\"Year: 1992<br />yield:  7.4276<br />country: Peru\",\"Year: 1993<br />yield:  8.3920<br />country: Peru\",\"Year: 1994<br />yield:  9.3738<br />country: Peru\",\"Year: 1995<br />yield:  9.7817<br />country: Peru\",\"Year: 1996<br />yield: 10.0629<br />country: Peru\",\"Year: 1997<br />yield:  9.6703<br />country: Peru\",\"Year: 1998<br />yield:  9.7887<br />country: Peru\",\"Year: 1999<br />yield: 11.2513<br />country: Peru\",\"Year: 2000<br />yield: 11.5040<br />country: Peru\",\"Year: 2001<br />yield: 11.4862<br />country: Peru\",\"Year: 2002<br />yield: 12.1751<br />country: Peru\",\"Year: 2003<br />yield: 12.1854<br />country: Peru\",\"Year: 2004<br />yield: 12.1901<br />country: Peru\",\"Year: 2005<br />yield: 12.4584<br />country: Peru\",\"Year: 2006<br />yield: 12.4533<br />country: Peru\",\"Year: 2007<br />yield: 12.6342<br />country: Peru\",\"Year: 2008<br />yield: 12.9138<br />country: Peru\",\"Year: 2009<br />yield: 13.3353<br />country: Peru\",\"Year: 2010<br />yield: 13.1588<br />country: Peru\",\"Year: 2011<br />yield: 13.7379<br />country: Peru\",\"Year: 2012<br />yield: 14.3316<br />country: Peru\",\"Year: 2013<br />yield: 14.4125<br />country: Peru\",\"Year: 2014<br />yield: 14.7779<br />country: Peru\",\"Year: 2015<br />yield: 14.9122<br />country: Peru\",\"Year: 2016<br />yield: 14.5293<br />country: Peru\",\"Year: 2017<br />yield: 15.3875<br />country: Peru\",\"Year: 2018<br />yield: 15.8503<br />country: Peru\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(165,138,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Peru\",\"legendgroup\":\"Peru\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[4.0929,4.3106,3.7074,4.2759,3.8777,3.9012,4.3249,3.767,4.0456,4.1791,4.0119,4.0856,4.104,4.2697,4.383,4.2835,4.4212,4.0933,4.2634,4.3034,4.7253,4.564,4.1944,4.8426,4.5575,4.5045,5.0927,5.1505,5.1166,5.229,5.1416,4.9812,5.4506,5.8525,5.618,5.7198,6.1154,5.7558,6.2514,6.5901,6.6941,6.6876,6.7942,6.4401,6.8971,6.8732,6.6817,7.3089,7.3926,7.285,7.298,7.7851,7.7112,7.5953,7.8884,7.5453,7.3091,8.124],\"text\":[\"Year: 1961<br />yield:  4.0929<br />country: Peru\",\"Year: 1962<br />yield:  4.3106<br />country: Peru\",\"Year: 1963<br />yield:  3.7074<br />country: Peru\",\"Year: 1964<br />yield:  4.2759<br />country: Peru\",\"Year: 1965<br />yield:  3.8777<br />country: Peru\",\"Year: 1966<br />yield:  3.9012<br />country: Peru\",\"Year: 1967<br />yield:  4.3249<br />country: Peru\",\"Year: 1968<br />yield:  3.7670<br />country: Peru\",\"Year: 1969<br />yield:  4.0456<br />country: Peru\",\"Year: 1970<br />yield:  4.1791<br />country: Peru\",\"Year: 1971<br />yield:  4.0119<br />country: Peru\",\"Year: 1972<br />yield:  4.0856<br />country: Peru\",\"Year: 1973<br />yield:  4.1040<br />country: Peru\",\"Year: 1974<br />yield:  4.2697<br />country: Peru\",\"Year: 1975<br />yield:  4.3830<br />country: Peru\",\"Year: 1976<br />yield:  4.2835<br />country: Peru\",\"Year: 1977<br />yield:  4.4212<br />country: Peru\",\"Year: 1978<br />yield:  4.0933<br />country: Peru\",\"Year: 1979<br />yield:  4.2634<br />country: Peru\",\"Year: 1980<br />yield:  4.3034<br />country: Peru\",\"Year: 1981<br />yield:  4.7253<br />country: Peru\",\"Year: 1982<br />yield:  4.5640<br />country: Peru\",\"Year: 1983<br />yield:  4.1944<br />country: Peru\",\"Year: 1984<br />yield:  4.8426<br />country: Peru\",\"Year: 1985<br />yield:  4.5575<br />country: Peru\",\"Year: 1986<br />yield:  4.5045<br />country: Peru\",\"Year: 1987<br />yield:  5.0927<br />country: Peru\",\"Year: 1988<br />yield:  5.1505<br />country: Peru\",\"Year: 1989<br />yield:  5.1166<br />country: Peru\",\"Year: 1990<br />yield:  5.2290<br />country: Peru\",\"Year: 1991<br />yield:  5.1416<br />country: Peru\",\"Year: 1992<br />yield:  4.9812<br />country: Peru\",\"Year: 1993<br />yield:  5.4506<br />country: Peru\",\"Year: 1994<br />yield:  5.8525<br />country: Peru\",\"Year: 1995<br />yield:  5.6180<br />country: Peru\",\"Year: 1996<br />yield:  5.7198<br />country: Peru\",\"Year: 1997<br />yield:  6.1154<br />country: Peru\",\"Year: 1998<br />yield:  5.7558<br />country: Peru\",\"Year: 1999<br />yield:  6.2514<br />country: Peru\",\"Year: 2000<br />yield:  6.5901<br />country: Peru\",\"Year: 2001<br />yield:  6.6941<br />country: Peru\",\"Year: 2002<br />yield:  6.6876<br />country: Peru\",\"Year: 2003<br />yield:  6.7942<br />country: Peru\",\"Year: 2004<br />yield:  6.4401<br />country: Peru\",\"Year: 2005<br />yield:  6.8971<br />country: Peru\",\"Year: 2006<br />yield:  6.8732<br />country: Peru\",\"Year: 2007<br />yield:  6.6817<br />country: Peru\",\"Year: 2008<br />yield:  7.3089<br />country: Peru\",\"Year: 2009<br />yield:  7.3926<br />country: Peru\",\"Year: 2010<br />yield:  7.2850<br />country: Peru\",\"Year: 2011<br />yield:  7.2980<br />country: Peru\",\"Year: 2012<br />yield:  7.7851<br />country: Peru\",\"Year: 2013<br />yield:  7.7112<br />country: Peru\",\"Year: 2014<br />yield:  7.5953<br />country: Peru\",\"Year: 2015<br />yield:  7.8884<br />country: Peru\",\"Year: 2016<br />yield:  7.5453<br />country: Peru\",\"Year: 2017<br />yield:  7.3091<br />country: Peru\",\"Year: 2018<br />yield:  8.1240<br />country: Peru\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(165,138,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Peru\",\"legendgroup\":\"Peru\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[1.0012,0.9926,1.0157,0.9588,0.958,0.9253,0.952,0.83,0.9327,0.9203,0.8823,0.8901,0.9011,0.9241,0.9453,0.952,1.0023,1.0076,1.0606,0.9394,1.0225,1.0597,0.9474,1.03,1.1388,1.2362,1.2758,1.3228,1.3551,1.0847,0.8553,1.3304,1.4812,1.242,1.2643,1.2499,1.115,1.1648,1.2877,1.2797,1.2465,1.3456,1.3779,1.3872,1.344,1.336,1.2562,1.3839,1.4315,1.4224,1.4719,1.4891,1.4976,1.5554,1.5529,1.5027,1.505,1.5405],\"text\":[\"Year: 1961<br />yield:  1.0012<br />country: Peru\",\"Year: 1962<br />yield:  0.9926<br />country: Peru\",\"Year: 1963<br />yield:  1.0157<br />country: Peru\",\"Year: 1964<br />yield:  0.9588<br />country: Peru\",\"Year: 1965<br />yield:  0.9580<br />country: Peru\",\"Year: 1966<br />yield:  0.9253<br />country: Peru\",\"Year: 1967<br />yield:  0.9520<br />country: Peru\",\"Year: 1968<br />yield:  0.8300<br />country: Peru\",\"Year: 1969<br />yield:  0.9327<br />country: Peru\",\"Year: 1970<br />yield:  0.9203<br />country: Peru\",\"Year: 1971<br />yield:  0.8823<br />country: Peru\",\"Year: 1972<br />yield:  0.8901<br />country: Peru\",\"Year: 1973<br />yield:  0.9011<br />country: Peru\",\"Year: 1974<br />yield:  0.9241<br />country: Peru\",\"Year: 1975<br />yield:  0.9453<br />country: Peru\",\"Year: 1976<br />yield:  0.9520<br />country: Peru\",\"Year: 1977<br />yield:  1.0023<br />country: Peru\",\"Year: 1978<br />yield:  1.0076<br />country: Peru\",\"Year: 1979<br />yield:  1.0606<br />country: Peru\",\"Year: 1980<br />yield:  0.9394<br />country: Peru\",\"Year: 1981<br />yield:  1.0225<br />country: Peru\",\"Year: 1982<br />yield:  1.0597<br />country: Peru\",\"Year: 1983<br />yield:  0.9474<br />country: Peru\",\"Year: 1984<br />yield:  1.0300<br />country: Peru\",\"Year: 1985<br />yield:  1.1388<br />country: Peru\",\"Year: 1986<br />yield:  1.2362<br />country: Peru\",\"Year: 1987<br />yield:  1.2758<br />country: Peru\",\"Year: 1988<br />yield:  1.3228<br />country: Peru\",\"Year: 1989<br />yield:  1.3551<br />country: Peru\",\"Year: 1990<br />yield:  1.0847<br />country: Peru\",\"Year: 1991<br />yield:  0.8553<br />country: Peru\",\"Year: 1992<br />yield:  1.3304<br />country: Peru\",\"Year: 1993<br />yield:  1.4812<br />country: Peru\",\"Year: 1994<br />yield:  1.2420<br />country: Peru\",\"Year: 1995<br />yield:  1.2643<br />country: Peru\",\"Year: 1996<br />yield:  1.2499<br />country: Peru\",\"Year: 1997<br />yield:  1.1150<br />country: Peru\",\"Year: 1998<br />yield:  1.1648<br />country: Peru\",\"Year: 1999<br />yield:  1.2877<br />country: Peru\",\"Year: 2000<br />yield:  1.2797<br />country: Peru\",\"Year: 2001<br />yield:  1.2465<br />country: Peru\",\"Year: 2002<br />yield:  1.3456<br />country: Peru\",\"Year: 2003<br />yield:  1.3779<br />country: Peru\",\"Year: 2004<br />yield:  1.3872<br />country: Peru\",\"Year: 2005<br />yield:  1.3440<br />country: Peru\",\"Year: 2006<br />yield:  1.3360<br />country: Peru\",\"Year: 2007<br />yield:  1.2562<br />country: Peru\",\"Year: 2008<br />yield:  1.3839<br />country: Peru\",\"Year: 2009<br />yield:  1.4315<br />country: Peru\",\"Year: 2010<br />yield:  1.4224<br />country: Peru\",\"Year: 2011<br />yield:  1.4719<br />country: Peru\",\"Year: 2012<br />yield:  1.4891<br />country: Peru\",\"Year: 2013<br />yield:  1.4976<br />country: Peru\",\"Year: 2014<br />yield:  1.5554<br />country: Peru\",\"Year: 2015<br />yield:  1.5529<br />country: Peru\",\"Year: 2016<br />yield:  1.5027<br />country: Peru\",\"Year: 2017<br />yield:  1.5050<br />country: Peru\",\"Year: 2018<br />yield:  1.5405<br />country: Peru\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(165,138,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Peru\",\"legendgroup\":\"Peru\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[0.7864,0.5806,0.8707,0.5446,0.3275,0.789,0.517,0.428,0.737,0.8342,0.9213,0.7801,1.0123,1.1693,1.0278,1.2206,0.8766,1.0519,0.7577,0.9538,1.2365,1.025,1.114,1.3441,1.2066,0.9913,1.185,1.592,1.2278,1.851,1.78,1.5613,1.9631,1.6279,2.4528,2.1712,2.6444,3.3715,4.0894,1.5296,4.6643,3.3552,4.5855,4.964,4.1419,4.1837,5.7541,4.1526,3.0834,5.5115,3.5377,4.2615,5.6309,4.3059,5.7711,7.1364,3.8625,7.6262],\"text\":[\"Year: 1961<br />yield:  0.7864<br />country: Uruguay\",\"Year: 1962<br />yield:  0.5806<br />country: Uruguay\",\"Year: 1963<br />yield:  0.8707<br />country: Uruguay\",\"Year: 1964<br />yield:  0.5446<br />country: Uruguay\",\"Year: 1965<br />yield:  0.3275<br />country: Uruguay\",\"Year: 1966<br />yield:  0.7890<br />country: Uruguay\",\"Year: 1967<br />yield:  0.5170<br />country: Uruguay\",\"Year: 1968<br />yield:  0.4280<br />country: Uruguay\",\"Year: 1969<br />yield:  0.7370<br />country: Uruguay\",\"Year: 1970<br />yield:  0.8342<br />country: Uruguay\",\"Year: 1971<br />yield:  0.9213<br />country: Uruguay\",\"Year: 1972<br />yield:  0.7801<br />country: Uruguay\",\"Year: 1973<br />yield:  1.0123<br />country: Uruguay\",\"Year: 1974<br />yield:  1.1693<br />country: Uruguay\",\"Year: 1975<br />yield:  1.0278<br />country: Uruguay\",\"Year: 1976<br />yield:  1.2206<br />country: Uruguay\",\"Year: 1977<br />yield:  0.8766<br />country: Uruguay\",\"Year: 1978<br />yield:  1.0519<br />country: Uruguay\",\"Year: 1979<br />yield:  0.7577<br />country: Uruguay\",\"Year: 1980<br />yield:  0.9538<br />country: Uruguay\",\"Year: 1981<br />yield:  1.2365<br />country: Uruguay\",\"Year: 1982<br />yield:  1.0250<br />country: Uruguay\",\"Year: 1983<br />yield:  1.1140<br />country: Uruguay\",\"Year: 1984<br />yield:  1.3441<br />country: Uruguay\",\"Year: 1985<br />yield:  1.2066<br />country: Uruguay\",\"Year: 1986<br />yield:  0.9913<br />country: Uruguay\",\"Year: 1987<br />yield:  1.1850<br />country: Uruguay\",\"Year: 1988<br />yield:  1.5920<br />country: Uruguay\",\"Year: 1989<br />yield:  1.2278<br />country: Uruguay\",\"Year: 1990<br />yield:  1.8510<br />country: Uruguay\",\"Year: 1991<br />yield:  1.7800<br />country: Uruguay\",\"Year: 1992<br />yield:  1.5613<br />country: Uruguay\",\"Year: 1993<br />yield:  1.9631<br />country: Uruguay\",\"Year: 1994<br />yield:  1.6279<br />country: Uruguay\",\"Year: 1995<br />yield:  2.4528<br />country: Uruguay\",\"Year: 1996<br />yield:  2.1712<br />country: Uruguay\",\"Year: 1997<br />yield:  2.6444<br />country: Uruguay\",\"Year: 1998<br />yield:  3.3715<br />country: Uruguay\",\"Year: 1999<br />yield:  4.0894<br />country: Uruguay\",\"Year: 2000<br />yield:  1.5296<br />country: Uruguay\",\"Year: 2001<br />yield:  4.6643<br />country: Uruguay\",\"Year: 2002<br />yield:  3.3552<br />country: Uruguay\",\"Year: 2003<br />yield:  4.5855<br />country: Uruguay\",\"Year: 2004<br />yield:  4.9640<br />country: Uruguay\",\"Year: 2005<br />yield:  4.1419<br />country: Uruguay\",\"Year: 2006<br />yield:  4.1837<br />country: Uruguay\",\"Year: 2007<br />yield:  5.7541<br />country: Uruguay\",\"Year: 2008<br />yield:  4.1526<br />country: Uruguay\",\"Year: 2009<br />yield:  3.0834<br />country: Uruguay\",\"Year: 2010<br />yield:  5.5115<br />country: Uruguay\",\"Year: 2011<br />yield:  3.5377<br />country: Uruguay\",\"Year: 2012<br />yield:  4.2615<br />country: Uruguay\",\"Year: 2013<br />yield:  5.6309<br />country: Uruguay\",\"Year: 2014<br />yield:  4.3059<br />country: Uruguay\",\"Year: 2015<br />yield:  5.7711<br />country: Uruguay\",\"Year: 2016<br />yield:  7.1364<br />country: Uruguay\",\"Year: 2017<br />yield:  3.8625<br />country: Uruguay\",\"Year: 2018<br />yield:  7.6262<br />country: Uruguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(251,97,215,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Uruguay\",\"legendgroup\":\"Uruguay\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[6.0415,4.4115,4.9572,4.052,4.8302,5.5702,4.7171,3.5049,6.1748,5.635,6.2674,4.5597,5.4358,4.9726,4.6892,6.4123,5.1085,5.2468,6.4157,4.9762,8.2972,7.0753,5.8452,7.7589,7.4991,6.3255,8.3475,7.3995,8.5786,9.5,10.1741,9.2262,8.5938,9.3306,10.0603,10.9417,15.0885,15.7532,16.3866,12.4074,14.6493,12.9399,16.2745,15.9905,18.933,17.2693,14.9353,16.9299,16.1006,20.0915,17.761,21.9891,22.4434,20.4308,17.2208,20.1175,19.8019,20.8783],\"text\":[\"Year: 1961<br />yield:  6.0415<br />country: Uruguay\",\"Year: 1962<br />yield:  4.4115<br />country: Uruguay\",\"Year: 1963<br />yield:  4.9572<br />country: Uruguay\",\"Year: 1964<br />yield:  4.0520<br />country: Uruguay\",\"Year: 1965<br />yield:  4.8302<br />country: Uruguay\",\"Year: 1966<br />yield:  5.5702<br />country: Uruguay\",\"Year: 1967<br />yield:  4.7171<br />country: Uruguay\",\"Year: 1968<br />yield:  3.5049<br />country: Uruguay\",\"Year: 1969<br />yield:  6.1748<br />country: Uruguay\",\"Year: 1970<br />yield:  5.6350<br />country: Uruguay\",\"Year: 1971<br />yield:  6.2674<br />country: Uruguay\",\"Year: 1972<br />yield:  4.5597<br />country: Uruguay\",\"Year: 1973<br />yield:  5.4358<br />country: Uruguay\",\"Year: 1974<br />yield:  4.9726<br />country: Uruguay\",\"Year: 1975<br />yield:  4.6892<br />country: Uruguay\",\"Year: 1976<br />yield:  6.4123<br />country: Uruguay\",\"Year: 1977<br />yield:  5.1085<br />country: Uruguay\",\"Year: 1978<br />yield:  5.2468<br />country: Uruguay\",\"Year: 1979<br />yield:  6.4157<br />country: Uruguay\",\"Year: 1980<br />yield:  4.9762<br />country: Uruguay\",\"Year: 1981<br />yield:  8.2972<br />country: Uruguay\",\"Year: 1982<br />yield:  7.0753<br />country: Uruguay\",\"Year: 1983<br />yield:  5.8452<br />country: Uruguay\",\"Year: 1984<br />yield:  7.7589<br />country: Uruguay\",\"Year: 1985<br />yield:  7.4991<br />country: Uruguay\",\"Year: 1986<br />yield:  6.3255<br />country: Uruguay\",\"Year: 1987<br />yield:  8.3475<br />country: Uruguay\",\"Year: 1988<br />yield:  7.3995<br />country: Uruguay\",\"Year: 1989<br />yield:  8.5786<br />country: Uruguay\",\"Year: 1990<br />yield:  9.5000<br />country: Uruguay\",\"Year: 1991<br />yield: 10.1741<br />country: Uruguay\",\"Year: 1992<br />yield:  9.2262<br />country: Uruguay\",\"Year: 1993<br />yield:  8.5938<br />country: Uruguay\",\"Year: 1994<br />yield:  9.3306<br />country: Uruguay\",\"Year: 1995<br />yield: 10.0603<br />country: Uruguay\",\"Year: 1996<br />yield: 10.9417<br />country: Uruguay\",\"Year: 1997<br />yield: 15.0885<br />country: Uruguay\",\"Year: 1998<br />yield: 15.7532<br />country: Uruguay\",\"Year: 1999<br />yield: 16.3866<br />country: Uruguay\",\"Year: 2000<br />yield: 12.4074<br />country: Uruguay\",\"Year: 2001<br />yield: 14.6493<br />country: Uruguay\",\"Year: 2002<br />yield: 12.9399<br />country: Uruguay\",\"Year: 2003<br />yield: 16.2745<br />country: Uruguay\",\"Year: 2004<br />yield: 15.9905<br />country: Uruguay\",\"Year: 2005<br />yield: 18.9330<br />country: Uruguay\",\"Year: 2006<br />yield: 17.2693<br />country: Uruguay\",\"Year: 2007<br />yield: 14.9353<br />country: Uruguay\",\"Year: 2008<br />yield: 16.9299<br />country: Uruguay\",\"Year: 2009<br />yield: 16.1006<br />country: Uruguay\",\"Year: 2010<br />yield: 20.0915<br />country: Uruguay\",\"Year: 2011<br />yield: 17.7610<br />country: Uruguay\",\"Year: 2012<br />yield: 21.9891<br />country: Uruguay\",\"Year: 2013<br />yield: 22.4434<br />country: Uruguay\",\"Year: 2014<br />yield: 20.4308<br />country: Uruguay\",\"Year: 2015<br />yield: 17.2208<br />country: Uruguay\",\"Year: 2016<br />yield: 20.1175<br />country: Uruguay\",\"Year: 2017<br />yield: 19.8019<br />country: Uruguay\",\"Year: 2018<br />yield: 20.8783<br />country: Uruguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(251,97,215,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Uruguay\",\"legendgroup\":\"Uruguay\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[3.5408,3.4126,3.6687,2.293,3.2708,2.7459,3.4029,3.3973,3.9166,3.8836,3.8894,4.1095,3.964,3.7023,3.954,4.1378,4.0161,3.8651,4.1322,4.2696,5.3058,6.0315,4.6057,4.3133,4.9535,4.7842,4.2253,4.7077,5.6445,4.4474,4.7767,4.7557,5.1717,4.9158,5.5099,6.4684,6.5839,5.0862,6.383,6.384,6.7037,5.8632,5.9042,6.7712,6.6005,7.2893,7.8796,7.8989,8.01,7.0954,8.3827,7.8513,7.8812,8.0544,8.0896,8.0938,8.5711,8.5],\"text\":[\"Year: 1961<br />yield:  3.5408<br />country: Uruguay\",\"Year: 1962<br />yield:  3.4126<br />country: Uruguay\",\"Year: 1963<br />yield:  3.6687<br />country: Uruguay\",\"Year: 1964<br />yield:  2.2930<br />country: Uruguay\",\"Year: 1965<br />yield:  3.2708<br />country: Uruguay\",\"Year: 1966<br />yield:  2.7459<br />country: Uruguay\",\"Year: 1967<br />yield:  3.4029<br />country: Uruguay\",\"Year: 1968<br />yield:  3.3973<br />country: Uruguay\",\"Year: 1969<br />yield:  3.9166<br />country: Uruguay\",\"Year: 1970<br />yield:  3.8836<br />country: Uruguay\",\"Year: 1971<br />yield:  3.8894<br />country: Uruguay\",\"Year: 1972<br />yield:  4.1095<br />country: Uruguay\",\"Year: 1973<br />yield:  3.9640<br />country: Uruguay\",\"Year: 1974<br />yield:  3.7023<br />country: Uruguay\",\"Year: 1975<br />yield:  3.9540<br />country: Uruguay\",\"Year: 1976<br />yield:  4.1378<br />country: Uruguay\",\"Year: 1977<br />yield:  4.0161<br />country: Uruguay\",\"Year: 1978<br />yield:  3.8651<br />country: Uruguay\",\"Year: 1979<br />yield:  4.1322<br />country: Uruguay\",\"Year: 1980<br />yield:  4.2696<br />country: Uruguay\",\"Year: 1981<br />yield:  5.3058<br />country: Uruguay\",\"Year: 1982<br />yield:  6.0315<br />country: Uruguay\",\"Year: 1983<br />yield:  4.6057<br />country: Uruguay\",\"Year: 1984<br />yield:  4.3133<br />country: Uruguay\",\"Year: 1985<br />yield:  4.9535<br />country: Uruguay\",\"Year: 1986<br />yield:  4.7842<br />country: Uruguay\",\"Year: 1987<br />yield:  4.2253<br />country: Uruguay\",\"Year: 1988<br />yield:  4.7077<br />country: Uruguay\",\"Year: 1989<br />yield:  5.6445<br />country: Uruguay\",\"Year: 1990<br />yield:  4.4474<br />country: Uruguay\",\"Year: 1991<br />yield:  4.7767<br />country: Uruguay\",\"Year: 1992<br />yield:  4.7557<br />country: Uruguay\",\"Year: 1993<br />yield:  5.1717<br />country: Uruguay\",\"Year: 1994<br />yield:  4.9158<br />country: Uruguay\",\"Year: 1995<br />yield:  5.5099<br />country: Uruguay\",\"Year: 1996<br />yield:  6.4684<br />country: Uruguay\",\"Year: 1997<br />yield:  6.5839<br />country: Uruguay\",\"Year: 1998<br />yield:  5.0862<br />country: Uruguay\",\"Year: 1999<br />yield:  6.3830<br />country: Uruguay\",\"Year: 2000<br />yield:  6.3840<br />country: Uruguay\",\"Year: 2001<br />yield:  6.7037<br />country: Uruguay\",\"Year: 2002<br />yield:  5.8632<br />country: Uruguay\",\"Year: 2003<br />yield:  5.9042<br />country: Uruguay\",\"Year: 2004<br />yield:  6.7712<br />country: Uruguay\",\"Year: 2005<br />yield:  6.6005<br />country: Uruguay\",\"Year: 2006<br />yield:  7.2893<br />country: Uruguay\",\"Year: 2007<br />yield:  7.8796<br />country: Uruguay\",\"Year: 2008<br />yield:  7.8989<br />country: Uruguay\",\"Year: 2009<br />yield:  8.0100<br />country: Uruguay\",\"Year: 2010<br />yield:  7.0954<br />country: Uruguay\",\"Year: 2011<br />yield:  8.3827<br />country: Uruguay\",\"Year: 2012<br />yield:  7.8513<br />country: Uruguay\",\"Year: 2013<br />yield:  7.8812<br />country: Uruguay\",\"Year: 2014<br />yield:  8.0544<br />country: Uruguay\",\"Year: 2015<br />yield:  8.0896<br />country: Uruguay\",\"Year: 2016<br />yield:  8.0938<br />country: Uruguay\",\"Year: 2017<br />yield:  8.5711<br />country: Uruguay\",\"Year: 2018<br />yield:  8.5000<br />country: Uruguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(251,97,215,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Uruguay\",\"legendgroup\":\"Uruguay\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018],\"y\":[0.8523,1.1289,0.6683,1.2252,1.1342,0.8662,0.6475,0.8829,0.9921,1.1533,0.8881,1.0083,1.0482,1.2253,0.9999,0.9938,0.539,0.7952,1.3623,1.3485,1.3107,1.5231,1.6565,1.5436,1.1627,1.243,1.8425,2.341,2.392,1.851,1.6135,2.3035,1.6018,2.5653,2.3359,2.5957,1.9843,2.8929,1.9537,2.5344,1.1488,2,1.5011,2.7698,2.9704,2.9583,3.1603,2.842,2.856,3.3583,3.2196,3.3979,2.1822,3.3177,2.6967,3.6082,3.5209,2.3656],\"text\":[\"Year: 1961<br />yield:  0.8523<br />country: Uruguay\",\"Year: 1962<br />yield:  1.1289<br />country: Uruguay\",\"Year: 1963<br />yield:  0.6683<br />country: Uruguay\",\"Year: 1964<br />yield:  1.2252<br />country: Uruguay\",\"Year: 1965<br />yield:  1.1342<br />country: Uruguay\",\"Year: 1966<br />yield:  0.8662<br />country: Uruguay\",\"Year: 1967<br />yield:  0.6475<br />country: Uruguay\",\"Year: 1968<br />yield:  0.8829<br />country: Uruguay\",\"Year: 1969<br />yield:  0.9921<br />country: Uruguay\",\"Year: 1970<br />yield:  1.1533<br />country: Uruguay\",\"Year: 1971<br />yield:  0.8881<br />country: Uruguay\",\"Year: 1972<br />yield:  1.0083<br />country: Uruguay\",\"Year: 1973<br />yield:  1.0482<br />country: Uruguay\",\"Year: 1974<br />yield:  1.2253<br />country: Uruguay\",\"Year: 1975<br />yield:  0.9999<br />country: Uruguay\",\"Year: 1976<br />yield:  0.9938<br />country: Uruguay\",\"Year: 1977<br />yield:  0.5390<br />country: Uruguay\",\"Year: 1978<br />yield:  0.7952<br />country: Uruguay\",\"Year: 1979<br />yield:  1.3623<br />country: Uruguay\",\"Year: 1980<br />yield:  1.3485<br />country: Uruguay\",\"Year: 1981<br />yield:  1.3107<br />country: Uruguay\",\"Year: 1982<br />yield:  1.5231<br />country: Uruguay\",\"Year: 1983<br />yield:  1.6565<br />country: Uruguay\",\"Year: 1984<br />yield:  1.5436<br />country: Uruguay\",\"Year: 1985<br />yield:  1.1627<br />country: Uruguay\",\"Year: 1986<br />yield:  1.2430<br />country: Uruguay\",\"Year: 1987<br />yield:  1.8425<br />country: Uruguay\",\"Year: 1988<br />yield:  2.3410<br />country: Uruguay\",\"Year: 1989<br />yield:  2.3920<br />country: Uruguay\",\"Year: 1990<br />yield:  1.8510<br />country: Uruguay\",\"Year: 1991<br />yield:  1.6135<br />country: Uruguay\",\"Year: 1992<br />yield:  2.3035<br />country: Uruguay\",\"Year: 1993<br />yield:  1.6018<br />country: Uruguay\",\"Year: 1994<br />yield:  2.5653<br />country: Uruguay\",\"Year: 1995<br />yield:  2.3359<br />country: Uruguay\",\"Year: 1996<br />yield:  2.5957<br />country: Uruguay\",\"Year: 1997<br />yield:  1.9843<br />country: Uruguay\",\"Year: 1998<br />yield:  2.8929<br />country: Uruguay\",\"Year: 1999<br />yield:  1.9537<br />country: Uruguay\",\"Year: 2000<br />yield:  2.5344<br />country: Uruguay\",\"Year: 2001<br />yield:  1.1488<br />country: Uruguay\",\"Year: 2002<br />yield:  2.0000<br />country: Uruguay\",\"Year: 2003<br />yield:  1.5011<br />country: Uruguay\",\"Year: 2004<br />yield:  2.7698<br />country: Uruguay\",\"Year: 2005<br />yield:  2.9704<br />country: Uruguay\",\"Year: 2006<br />yield:  2.9583<br />country: Uruguay\",\"Year: 2007<br />yield:  3.1603<br />country: Uruguay\",\"Year: 2008<br />yield:  2.8420<br />country: Uruguay\",\"Year: 2009<br />yield:  2.8560<br />country: Uruguay\",\"Year: 2010<br />yield:  3.3583<br />country: Uruguay\",\"Year: 2011<br />yield:  3.2196<br />country: Uruguay\",\"Year: 2012<br />yield:  3.3979<br />country: Uruguay\",\"Year: 2013<br />yield:  2.1822<br />country: Uruguay\",\"Year: 2014<br />yield:  3.3177<br />country: Uruguay\",\"Year: 2015<br />yield:  2.6967<br />country: Uruguay\",\"Year: 2016<br />yield:  3.6082<br />country: Uruguay\",\"Year: 2017<br />yield:  3.5209<br />country: Uruguay\",\"Year: 2018<br />yield:  2.3656<br />country: Uruguay\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.88976377952756,\"color\":\"rgba(251,97,215,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"name\":\"Uruguay\",\"legendgroup\":\"Uruguay\",\"showlegend\":false,\"xaxis\":\"x2\",\"yaxis\":\"y2\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":39.8660578386606,\"r\":7.30593607305936,\"b\":42.130898021309,\"l\":37.2602739726027},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,0.492389649923896],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1958.15,2020.85],\"tickmode\":\"array\",\"ticktext\":[\"1960\",\"1980\",\"2000\",\"2020\"],\"tickvals\":[1960,1980,2000,2020],\"categoryorder\":\"array\",\"categoryarray\":[\"1960\",\"1980\",\"2000\",\"2020\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"annotations\":[{\"text\":\"Year\",\"x\":0.5,\"y\":0,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"top\",\"annotationType\":\"axis\",\"yshift\":-21.9178082191781},{\"text\":\"Yield (t ha)\",\"x\":0,\"y\":0.5,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-90,\"xanchor\":\"right\",\"yanchor\":\"center\",\"annotationType\":\"axis\",\"xshift\":-21.9178082191781},{\"text\":\"Maize\",\"x\":0.246194824961948,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.689497716895},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Potatoes\",\"x\":0.753805175038052,\"y\":1,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.689497716895},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Rice\",\"x\":0.246194824961948,\"y\":0.467021816336885,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.689497716895},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"},{\"text\":\"Wheat\",\"x\":0.753805175038052,\"y\":0.467021816336885,\"showarrow\":false,\"ax\":0,\"ay\":0,\"font\":{\"color\":\"rgba(26,26,26,1)\",\"family\":\"\",\"size\":11.689497716895},\"xref\":\"paper\",\"yref\":\"paper\",\"textangle\":-0,\"xanchor\":\"center\",\"yanchor\":\"bottom\"}],\"yaxis\":{\"domain\":[0.532978183663115,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.27129,33.90209],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\"],\"tickvals\":[0,10,20,30],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.492389649923896,\"y0\":0.532978183663115,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":\"rgba(217,217,217,1)\",\"line\":{\"color\":\"transparent\",\"width\":0.66417600664176,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.492389649923896,\"y0\":0,\"y1\":23.37899543379,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.507610350076104,\"x1\":1,\"y0\":0.532978183663115,\"y1\":1},{\"type\":\"rect\",\"fillcolor\":\"rgba(217,217,217,1)\",\"line\":{\"color\":\"transparent\",\"width\":0.66417600664176,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.507610350076104,\"x1\":1,\"y0\":0,\"y1\":23.37899543379,\"yanchor\":1,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.492389649923896,\"y0\":0,\"y1\":0.467021816336885},{\"type\":\"rect\",\"fillcolor\":\"rgba(217,217,217,1)\",\"line\":{\"color\":\"transparent\",\"width\":0.66417600664176,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":0.492389649923896,\"y0\":0,\"y1\":23.37899543379,\"yanchor\":0.467021816336885,\"ysizemode\":\"pixel\"},{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.507610350076104,\"x1\":1,\"y0\":0,\"y1\":0.467021816336885},{\"type\":\"rect\",\"fillcolor\":\"rgba(217,217,217,1)\",\"line\":{\"color\":\"transparent\",\"width\":0.66417600664176,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0.507610350076104,\"x1\":1,\"y0\":0,\"y1\":23.37899543379,\"yanchor\":0.467021816336885,\"ysizemode\":\"pixel\"}],\"xaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[1958.15,2020.85],\"tickmode\":\"array\",\"ticktext\":[\"1960\",\"1980\",\"2000\",\"2020\"],\"tickvals\":[1960,1980,2000,2020],\"categoryorder\":\"array\",\"categoryarray\":[\"1960\",\"1980\",\"2000\",\"2020\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0.507610350076104,1],\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"y2\",\"title\":\"\",\"hoverformat\":\".2f\"},\"yaxis2\":{\"type\":\"linear\",\"autorange\":false,\"range\":[-1.27129,33.90209],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\"],\"tickvals\":[0,10,20,30],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"domain\":[0,0.467021816336885],\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176,\"zeroline\":false,\"anchor\":\"x\",\"title\":\"\",\"hoverformat\":\".2f\"},\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"country\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"35bd430ac43b\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"scatter\"}},\"cur_data\":\"35bd430ac43b\",\"visdat\":{\"35bd430ac43b\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nEn la figura, se observa tendencias de rendimiento a traves del tiempo que corresponden para los cuatro cultivos. Por ejemplo, el rendimiento de papa en Argentina tiende a incrmentar 10 t ha^-1^ cada 20 años; sin embargo, en Bolivia las tendencias de rendimiento son constantes o sea no hay un incremento pronunciado a compararación de los países vecinos.\n\nTambién se puede realizar una gráfica para el último año. Para ello, se filtró el año 2018 de la base de datos `long_crops` con la función `filter(Year == 2018)`. Con estos datos, se generó una gráfica de barras.\n\n\n::: {.cell layout=\"l-body-outset\"}\n\n```{.r .cell-code}\nyearfs <- long_crops %>%\n  filter(Year == 2018)\n\n# seleccion de tema para la gráfica\ntheme_set(\n  theme_classic() +\n    theme(legend.position = \"top\")\n)\n\n#Generando gráfica de barras\np1 <- ggplot(yearfs, aes(x=country, y=yield, fill=crop)) +\n  geom_bar(stat=\"identity\", position = position_dodge()) +\n  labs(x = \"Países\", y = \"Yield (t ha)\")\nfig <- ggplotly(p1)\n\nfig\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-710e89cf9a1f7a3f8ee3\" style=\"width:100%;height:390px;\" class=\"plotly html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-710e89cf9a1f7a3f8ee3\">{\"x\":{\"data\":[{\"orientation\":\"v\",\"width\":[0.225,0.225,0.225000000000001,0.225000000000001,0.225,0.225,0.225],\"base\":[0,0,0,0,0,0,0],\"x\":[0.6625,1.6625,2.6625,3.6625,4.6625,5.6625,6.6625],\"y\":[6.0883,2.7282,5.1044,12.4706,4.995,3.4416,7.6262],\"text\":[\"country: Argentina<br />yield:  6.0883<br />crop: Maize\",\"country: Bolivia<br />yield:  2.7282<br />crop: Maize\",\"country: Brazil<br />yield:  5.1044<br />crop: Maize\",\"country: Chile<br />yield: 12.4706<br />crop: Maize\",\"country: Paraguay<br />yield:  4.9950<br />crop: Maize\",\"country: Peru<br />yield:  3.4416<br />crop: Maize\",\"country: Uruguay<br />yield:  7.6262<br />crop: Maize\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(248,118,109,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"Maize\",\"legendgroup\":\"Maize\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.225,0.225,0.225,0.225,0.225,0.225,0.225],\"base\":[0,0,0,0,0,0,0],\"x\":[0.8875,1.8875,2.8875,3.8875,4.8875,5.8875,6.8875],\"y\":[32.3033,6.4211,31.176,28.6749,14.4774,15.8503,20.8783],\"text\":[\"country: Argentina<br />yield: 32.3033<br />crop: Potatoes\",\"country: Bolivia<br />yield:  6.4211<br />crop: Potatoes\",\"country: Brazil<br />yield: 31.1760<br />crop: Potatoes\",\"country: Chile<br />yield: 28.6749<br />crop: Potatoes\",\"country: Paraguay<br />yield: 14.4774<br />crop: Potatoes\",\"country: Peru<br />yield: 15.8503<br />crop: Potatoes\",\"country: Uruguay<br />yield: 20.8783<br />crop: Potatoes\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(124,174,0,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"Potatoes\",\"legendgroup\":\"Potatoes\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.225,0.225,0.225,0.225,0.225,0.225,0.225],\"base\":[0,0,0,0,0,0,0],\"x\":[1.1125,2.1125,3.1125,4.1125,5.1125,6.1125,7.1125],\"y\":[6.903,3.1875,6.3123,6.531,6.3,8.124,8.5],\"text\":[\"country: Argentina<br />yield:  6.9030<br />crop: Rice\",\"country: Bolivia<br />yield:  3.1875<br />crop: Rice\",\"country: Brazil<br />yield:  6.3123<br />crop: Rice\",\"country: Chile<br />yield:  6.5310<br />crop: Rice\",\"country: Paraguay<br />yield:  6.3000<br />crop: Rice\",\"country: Peru<br />yield:  8.1240<br />crop: Rice\",\"country: Uruguay<br />yield:  8.5000<br />crop: Rice\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,191,196,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"Rice\",\"legendgroup\":\"Rice\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"orientation\":\"v\",\"width\":[0.225,0.225,0.225000000000001,0.225,0.225,0.225,0.225],\"base\":[0,0,0,0,0,0,0],\"x\":[1.3375,2.3375,3.3375,4.3375,5.3375,6.3375,7.3375],\"y\":[3.1806,1.5117,2.6238,6.2137,1.68,1.5405,2.3656],\"text\":[\"country: Argentina<br />yield:  3.1806<br />crop: Wheat\",\"country: Bolivia<br />yield:  1.5117<br />crop: Wheat\",\"country: Brazil<br />yield:  2.6238<br />crop: Wheat\",\"country: Chile<br />yield:  6.2137<br />crop: Wheat\",\"country: Paraguay<br />yield:  1.6800<br />crop: Wheat\",\"country: Peru<br />yield:  1.5405<br />crop: Wheat\",\"country: Uruguay<br />yield:  2.3656<br />crop: Wheat\"],\"type\":\"bar\",\"textposition\":\"none\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(199,124,255,1)\",\"line\":{\"width\":1.88976377952756,\"color\":\"transparent\"}},\"name\":\"Wheat\",\"legendgroup\":\"Wheat\",\"showlegend\":true,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":28.1765601217656,\"r\":7.30593607305936,\"b\":42.130898021309,\"l\":37.2602739726027},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.4,7.6],\"tickmode\":\"array\",\"ticktext\":[\"Argentina\",\"Bolivia\",\"Brazil\",\"Chile\",\"Paraguay\",\"Peru\",\"Uruguay\"],\"tickvals\":[1,2,3,4,5,6,7],\"categoryorder\":\"array\",\"categoryarray\":[\"Argentina\",\"Bolivia\",\"Brazil\",\"Chile\",\"Paraguay\",\"Peru\",\"Uruguay\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Países\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-1.615165,33.918465],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"10\",\"20\",\"30\"],\"tickvals\":[-2.22044604925031e-16,10,20,30],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"10\",\"20\",\"30\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.65296803652968,\"tickwidth\":0.66417600664176,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716895},\"tickangle\":-0,\"showline\":true,\"linecolor\":\"rgba(0,0,0,1)\",\"linewidth\":0.66417600664176,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Yield (t ha)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":true,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.88976377952756,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716895},\"title\":{\"text\":\"crop\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.6118721461187}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"35bd3b6daa31\":{\"x\":{},\"y\":{},\"fill\":{},\"type\":\"bar\"}},\"cur_data\":\"35bd3b6daa31\",\"visdat\":{\"35bd3b6daa31\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.2,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nEn esta figura se puede observar rendimientos de cuatro cultivos para el año 2018. En la cual, Argentina, Chile y Brasil tuvieron mayores rendimientos en el cultivo de papa; sin embargo, Bolivia se ubica en el último puesto en cuanto a rendimientos en los cuatro cultivos.\n\n## **Conclusión**\n\nLos usuarios de R pueden generar scripts reproducibles a base de este post. Extraer, ordenar y graficar datos con R, facilita obtener datos limpios y es más eficiente con los tiempos de trabajo.\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.5.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}